// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"chat_service/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPubSub creates a new instance of MockPubSub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPubSub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPubSub {
	mock := &MockPubSub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPubSub is an autogenerated mock type for the PubSub type
type MockPubSub struct {
	mock.Mock
}

type MockPubSub_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPubSub) EXPECT() *MockPubSub_Expecter {
	return &MockPubSub_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockPubSub
func (_mock *MockPubSub) Publish(ctx context.Context, channel string, msg *domain.Message) error {
	ret := _mock.Called(ctx, channel, msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *domain.Message) error); ok {
		r0 = returnFunc(ctx, channel, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPubSub_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockPubSub_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - channel string
//   - msg *domain.Message
func (_e *MockPubSub_Expecter) Publish(ctx interface{}, channel interface{}, msg interface{}) *MockPubSub_Publish_Call {
	return &MockPubSub_Publish_Call{Call: _e.mock.On("Publish", ctx, channel, msg)}
}

func (_c *MockPubSub_Publish_Call) Run(run func(ctx context.Context, channel string, msg *domain.Message)) *MockPubSub_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *domain.Message
		if args[2] != nil {
			arg2 = args[2].(*domain.Message)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPubSub_Publish_Call) Return(err error) *MockPubSub_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPubSub_Publish_Call) RunAndReturn(run func(ctx context.Context, channel string, msg *domain.Message) error) *MockPubSub_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockPubSub
func (_mock *MockPubSub) Subscribe(ctx context.Context, channel string) (chan *domain.Message, func()) {
	ret := _mock.Called(ctx, channel)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 chan *domain.Message
	var r1 func()
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (chan *domain.Message, func())); ok {
		return returnFunc(ctx, channel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) chan *domain.Message); ok {
		r0 = returnFunc(ctx, channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *domain.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) func()); ok {
		r1 = returnFunc(ctx, channel)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}
	return r0, r1
}

// MockPubSub_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockPubSub_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - channel string
func (_e *MockPubSub_Expecter) Subscribe(ctx interface{}, channel interface{}) *MockPubSub_Subscribe_Call {
	return &MockPubSub_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, channel)}
}

func (_c *MockPubSub_Subscribe_Call) Run(run func(ctx context.Context, channel string)) *MockPubSub_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPubSub_Subscribe_Call) Return(messageCh chan *domain.Message, fn func()) *MockPubSub_Subscribe_Call {
	_c.Call.Return(messageCh, fn)
	return _c
}

func (_c *MockPubSub_Subscribe_Call) RunAndReturn(run func(ctx context.Context, channel string) (chan *domain.Message, func())) *MockPubSub_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
