// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"chat_service/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// ChangeInviteAvailability provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) ChangeInviteAvailability(ctx context.Context, userID string, availability bool) error {
	ret := _mock.Called(ctx, userID, availability)

	if len(ret) == 0 {
		panic("no return value specified for ChangeInviteAvailability")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, userID, availability)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_ChangeInviteAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeInviteAvailability'
type MockUserRepository_ChangeInviteAvailability_Call struct {
	*mock.Call
}

// ChangeInviteAvailability is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - availability bool
func (_e *MockUserRepository_Expecter) ChangeInviteAvailability(ctx interface{}, userID interface{}, availability interface{}) *MockUserRepository_ChangeInviteAvailability_Call {
	return &MockUserRepository_ChangeInviteAvailability_Call{Call: _e.mock.On("ChangeInviteAvailability", ctx, userID, availability)}
}

func (_c *MockUserRepository_ChangeInviteAvailability_Call) Run(run func(ctx context.Context, userID string, availability bool)) *MockUserRepository_ChangeInviteAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_ChangeInviteAvailability_Call) Return(err error) *MockUserRepository_ChangeInviteAvailability_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_ChangeInviteAvailability_Call) RunAndReturn(run func(ctx context.Context, userID string, availability bool) error) *MockUserRepository_ChangeInviteAvailability_Call {
	_c.Call.Return(run)
	return _c
}

// GetInviteAvailability provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetInviteAvailability(ctx context.Context, userID string) (bool, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetInviteAvailability")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetInviteAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInviteAvailability'
type MockUserRepository_GetInviteAvailability_Call struct {
	*mock.Call
}

// GetInviteAvailability is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) GetInviteAvailability(ctx interface{}, userID interface{}) *MockUserRepository_GetInviteAvailability_Call {
	return &MockUserRepository_GetInviteAvailability_Call{Call: _e.mock.On("GetInviteAvailability", ctx, userID)}
}

func (_c *MockUserRepository_GetInviteAvailability_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepository_GetInviteAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetInviteAvailability_Call) Return(b bool, err error) *MockUserRepository_GetInviteAvailability_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepository_GetInviteAvailability_Call) RunAndReturn(run func(ctx context.Context, userID string) (bool, error)) *MockUserRepository_GetInviteAvailability_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserByID(ctx context.Context, userID string) (*domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockUserRepository_GetUserByID_Call {
	return &MockUserRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockUserRepository_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) Return(user *domain.User, err error) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*domain.User, error)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}
