// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFriendshipClient creates a new instance of MockFriendshipClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFriendshipClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFriendshipClient {
	mock := &MockFriendshipClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFriendshipClient is an autogenerated mock type for the FriendshipClient type
type MockFriendshipClient struct {
	mock.Mock
}

type MockFriendshipClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFriendshipClient) EXPECT() *MockFriendshipClient_Expecter {
	return &MockFriendshipClient_Expecter{mock: &_m.Mock}
}

// IsFriend provides a mock function for the type MockFriendshipClient
func (_mock *MockFriendshipClient) IsFriend(ctx context.Context, userID string, friendID string) (bool, error) {
	ret := _mock.Called(ctx, userID, friendID)

	if len(ret) == 0 {
		panic("no return value specified for IsFriend")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, userID, friendID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, userID, friendID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, friendID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipClient_IsFriend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFriend'
type MockFriendshipClient_IsFriend_Call struct {
	*mock.Call
}

// IsFriend is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - friendID string
func (_e *MockFriendshipClient_Expecter) IsFriend(ctx interface{}, userID interface{}, friendID interface{}) *MockFriendshipClient_IsFriend_Call {
	return &MockFriendshipClient_IsFriend_Call{Call: _e.mock.On("IsFriend", ctx, userID, friendID)}
}

func (_c *MockFriendshipClient_IsFriend_Call) Run(run func(ctx context.Context, userID string, friendID string)) *MockFriendshipClient_IsFriend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendshipClient_IsFriend_Call) Return(b bool, err error) *MockFriendshipClient_IsFriend_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFriendshipClient_IsFriend_Call) RunAndReturn(run func(ctx context.Context, userID string, friendID string) (bool, error)) *MockFriendshipClient_IsFriend_Call {
	_c.Call.Return(run)
	return _c
}
