// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"chat_service/internal/domain"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageRepository creates a new instance of MockMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageRepository {
	mock := &MockMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageRepository is an autogenerated mock type for the MessageRepository type
type MockMessageRepository struct {
	mock.Mock
}

type MockMessageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageRepository) EXPECT() *MockMessageRepository_Expecter {
	return &MockMessageRepository_Expecter{mock: &_m.Mock}
}

// GetMessagesBefore provides a mock function for the type MockMessageRepository
func (_mock *MockMessageRepository) GetMessagesBefore(ctx context.Context, roomID string, before time.Time) ([]*domain.Message, error) {
	ret := _mock.Called(ctx, roomID, before)

	if len(ret) == 0 {
		panic("no return value specified for GetMessagesBefore")
	}

	var r0 []*domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]*domain.Message, error)); ok {
		return returnFunc(ctx, roomID, before)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) []*domain.Message); ok {
		r0 = returnFunc(ctx, roomID, before)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, roomID, before)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessageRepository_GetMessagesBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessagesBefore'
type MockMessageRepository_GetMessagesBefore_Call struct {
	*mock.Call
}

// GetMessagesBefore is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - before time.Time
func (_e *MockMessageRepository_Expecter) GetMessagesBefore(ctx interface{}, roomID interface{}, before interface{}) *MockMessageRepository_GetMessagesBefore_Call {
	return &MockMessageRepository_GetMessagesBefore_Call{Call: _e.mock.On("GetMessagesBefore", ctx, roomID, before)}
}

func (_c *MockMessageRepository_GetMessagesBefore_Call) Run(run func(ctx context.Context, roomID string, before time.Time)) *MockMessageRepository_GetMessagesBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMessageRepository_GetMessagesBefore_Call) Return(messages []*domain.Message, err error) *MockMessageRepository_GetMessagesBefore_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockMessageRepository_GetMessagesBefore_Call) RunAndReturn(run func(ctx context.Context, roomID string, before time.Time) ([]*domain.Message, error)) *MockMessageRepository_GetMessagesBefore_Call {
	_c.Call.Return(run)
	return _c
}

// WriteMessage provides a mock function for the type MockMessageRepository
func (_mock *MockMessageRepository) WriteMessage(ctx context.Context, message *domain.Message) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for WriteMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Message) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageRepository_WriteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteMessage'
type MockMessageRepository_WriteMessage_Call struct {
	*mock.Call
}

// WriteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - message *domain.Message
func (_e *MockMessageRepository_Expecter) WriteMessage(ctx interface{}, message interface{}) *MockMessageRepository_WriteMessage_Call {
	return &MockMessageRepository_WriteMessage_Call{Call: _e.mock.On("WriteMessage", ctx, message)}
}

func (_c *MockMessageRepository_WriteMessage_Call) Run(run func(ctx context.Context, message *domain.Message)) *MockMessageRepository_WriteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Message
		if args[1] != nil {
			arg1 = args[1].(*domain.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessageRepository_WriteMessage_Call) Return(err error) *MockMessageRepository_WriteMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageRepository_WriteMessage_Call) RunAndReturn(run func(ctx context.Context, message *domain.Message) error) *MockMessageRepository_WriteMessage_Call {
	_c.Call.Return(run)
	return _c
}
