// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"chat_service/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRoomRepository creates a new instance of MockRoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomRepository {
	mock := &MockRoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoomRepository is an autogenerated mock type for the RoomRepository type
type MockRoomRepository struct {
	mock.Mock
}

type MockRoomRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomRepository) EXPECT() *MockRoomRepository_Expecter {
	return &MockRoomRepository_Expecter{mock: &_m.Mock}
}

// AddUser provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) AddUser(ctx context.Context, userID string, roomID string) error {
	ret := _mock.Called(ctx, userID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, roomID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoomRepository_AddUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUser'
type MockRoomRepository_AddUser_Call struct {
	*mock.Call
}

// AddUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - roomID string
func (_e *MockRoomRepository_Expecter) AddUser(ctx interface{}, userID interface{}, roomID interface{}) *MockRoomRepository_AddUser_Call {
	return &MockRoomRepository_AddUser_Call{Call: _e.mock.On("AddUser", ctx, userID, roomID)}
}

func (_c *MockRoomRepository_AddUser_Call) Run(run func(ctx context.Context, userID string, roomID string)) *MockRoomRepository_AddUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoomRepository_AddUser_Call) Return(err error) *MockRoomRepository_AddUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoomRepository_AddUser_Call) RunAndReturn(run func(ctx context.Context, userID string, roomID string) error) *MockRoomRepository_AddUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRoom provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) CreateRoom(ctx context.Context, name string, userID string) (*domain.Room, error) {
	ret := _mock.Called(ctx, name, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 *domain.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Room, error)); ok {
		return returnFunc(ctx, name, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.Room); ok {
		r0 = returnFunc(ctx, name, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomRepository_CreateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoom'
type MockRoomRepository_CreateRoom_Call struct {
	*mock.Call
}

// CreateRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - userID string
func (_e *MockRoomRepository_Expecter) CreateRoom(ctx interface{}, name interface{}, userID interface{}) *MockRoomRepository_CreateRoom_Call {
	return &MockRoomRepository_CreateRoom_Call{Call: _e.mock.On("CreateRoom", ctx, name, userID)}
}

func (_c *MockRoomRepository_CreateRoom_Call) Run(run func(ctx context.Context, name string, userID string)) *MockRoomRepository_CreateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoomRepository_CreateRoom_Call) Return(room *domain.Room, err error) *MockRoomRepository_CreateRoom_Call {
	_c.Call.Return(room, err)
	return _c
}

func (_c *MockRoomRepository_CreateRoom_Call) RunAndReturn(run func(ctx context.Context, name string, userID string) (*domain.Room, error)) *MockRoomRepository_CreateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRoom provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) DeleteRoom(ctx context.Context, roomID string) (*domain.Room, error) {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoom")
	}

	var r0 *domain.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Room, error)); ok {
		return returnFunc(ctx, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Room); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomRepository_DeleteRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRoom'
type MockRoomRepository_DeleteRoom_Call struct {
	*mock.Call
}

// DeleteRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockRoomRepository_Expecter) DeleteRoom(ctx interface{}, roomID interface{}) *MockRoomRepository_DeleteRoom_Call {
	return &MockRoomRepository_DeleteRoom_Call{Call: _e.mock.On("DeleteRoom", ctx, roomID)}
}

func (_c *MockRoomRepository_DeleteRoom_Call) Run(run func(ctx context.Context, roomID string)) *MockRoomRepository_DeleteRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomRepository_DeleteRoom_Call) Return(room *domain.Room, err error) *MockRoomRepository_DeleteRoom_Call {
	_c.Call.Return(room, err)
	return _c
}

func (_c *MockRoomRepository_DeleteRoom_Call) RunAndReturn(run func(ctx context.Context, roomID string) (*domain.Room, error)) *MockRoomRepository_DeleteRoom_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllRooms provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) GetAllRooms(ctx context.Context) ([]*domain.Room, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRooms")
	}

	var r0 []*domain.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.Room, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.Room); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomRepository_GetAllRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllRooms'
type MockRoomRepository_GetAllRooms_Call struct {
	*mock.Call
}

// GetAllRooms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoomRepository_Expecter) GetAllRooms(ctx interface{}) *MockRoomRepository_GetAllRooms_Call {
	return &MockRoomRepository_GetAllRooms_Call{Call: _e.mock.On("GetAllRooms", ctx)}
}

func (_c *MockRoomRepository_GetAllRooms_Call) Run(run func(ctx context.Context)) *MockRoomRepository_GetAllRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoomRepository_GetAllRooms_Call) Return(rooms []*domain.Room, err error) *MockRoomRepository_GetAllRooms_Call {
	_c.Call.Return(rooms, err)
	return _c
}

func (_c *MockRoomRepository_GetAllRooms_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.Room, error)) *MockRoomRepository_GetAllRooms_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoomsByUserID provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) GetRoomsByUserID(ctx context.Context, userID string) ([]*domain.Room, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomsByUserID")
	}

	var r0 []*domain.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Room, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Room); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomRepository_GetRoomsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoomsByUserID'
type MockRoomRepository_GetRoomsByUserID_Call struct {
	*mock.Call
}

// GetRoomsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRoomRepository_Expecter) GetRoomsByUserID(ctx interface{}, userID interface{}) *MockRoomRepository_GetRoomsByUserID_Call {
	return &MockRoomRepository_GetRoomsByUserID_Call{Call: _e.mock.On("GetRoomsByUserID", ctx, userID)}
}

func (_c *MockRoomRepository_GetRoomsByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockRoomRepository_GetRoomsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomRepository_GetRoomsByUserID_Call) Return(rooms []*domain.Room, err error) *MockRoomRepository_GetRoomsByUserID_Call {
	_c.Call.Return(rooms, err)
	return _c
}

func (_c *MockRoomRepository_GetRoomsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*domain.Room, error)) *MockRoomRepository_GetRoomsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersByRoomID provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) GetUsersByRoomID(ctx context.Context, roomID string) ([]*domain.User, error) {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByRoomID")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.User, error)); ok {
		return returnFunc(ctx, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.User); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomRepository_GetUsersByRoomID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersByRoomID'
type MockRoomRepository_GetUsersByRoomID_Call struct {
	*mock.Call
}

// GetUsersByRoomID is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockRoomRepository_Expecter) GetUsersByRoomID(ctx interface{}, roomID interface{}) *MockRoomRepository_GetUsersByRoomID_Call {
	return &MockRoomRepository_GetUsersByRoomID_Call{Call: _e.mock.On("GetUsersByRoomID", ctx, roomID)}
}

func (_c *MockRoomRepository_GetUsersByRoomID_Call) Run(run func(ctx context.Context, roomID string)) *MockRoomRepository_GetUsersByRoomID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomRepository_GetUsersByRoomID_Call) Return(users []*domain.User, err error) *MockRoomRepository_GetUsersByRoomID_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockRoomRepository_GetUsersByRoomID_Call) RunAndReturn(run func(ctx context.Context, roomID string) ([]*domain.User, error)) *MockRoomRepository_GetUsersByRoomID_Call {
	_c.Call.Return(run)
	return _c
}

// IsEmpty provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) IsEmpty(ctx context.Context, roomID string) (bool, error) {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for IsEmpty")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomRepository_IsEmpty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEmpty'
type MockRoomRepository_IsEmpty_Call struct {
	*mock.Call
}

// IsEmpty is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockRoomRepository_Expecter) IsEmpty(ctx interface{}, roomID interface{}) *MockRoomRepository_IsEmpty_Call {
	return &MockRoomRepository_IsEmpty_Call{Call: _e.mock.On("IsEmpty", ctx, roomID)}
}

func (_c *MockRoomRepository_IsEmpty_Call) Run(run func(ctx context.Context, roomID string)) *MockRoomRepository_IsEmpty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomRepository_IsEmpty_Call) Return(b bool, err error) *MockRoomRepository_IsEmpty_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRoomRepository_IsEmpty_Call) RunAndReturn(run func(ctx context.Context, roomID string) (bool, error)) *MockRoomRepository_IsEmpty_Call {
	_c.Call.Return(run)
	return _c
}

// IsMember provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) IsMember(ctx context.Context, userID string, roomID string) (bool, error) {
	ret := _mock.Called(ctx, userID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for IsMember")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, userID, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, userID, roomID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomRepository_IsMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMember'
type MockRoomRepository_IsMember_Call struct {
	*mock.Call
}

// IsMember is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - roomID string
func (_e *MockRoomRepository_Expecter) IsMember(ctx interface{}, userID interface{}, roomID interface{}) *MockRoomRepository_IsMember_Call {
	return &MockRoomRepository_IsMember_Call{Call: _e.mock.On("IsMember", ctx, userID, roomID)}
}

func (_c *MockRoomRepository_IsMember_Call) Run(run func(ctx context.Context, userID string, roomID string)) *MockRoomRepository_IsMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoomRepository_IsMember_Call) Return(b bool, err error) *MockRoomRepository_IsMember_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRoomRepository_IsMember_Call) RunAndReturn(run func(ctx context.Context, userID string, roomID string) (bool, error)) *MockRoomRepository_IsMember_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUser provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) RemoveUser(ctx context.Context, userID string, roomID string) error {
	ret := _mock.Called(ctx, userID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, roomID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoomRepository_RemoveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUser'
type MockRoomRepository_RemoveUser_Call struct {
	*mock.Call
}

// RemoveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - roomID string
func (_e *MockRoomRepository_Expecter) RemoveUser(ctx interface{}, userID interface{}, roomID interface{}) *MockRoomRepository_RemoveUser_Call {
	return &MockRoomRepository_RemoveUser_Call{Call: _e.mock.On("RemoveUser", ctx, userID, roomID)}
}

func (_c *MockRoomRepository_RemoveUser_Call) Run(run func(ctx context.Context, userID string, roomID string)) *MockRoomRepository_RemoveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoomRepository_RemoveUser_Call) Return(err error) *MockRoomRepository_RemoveUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoomRepository_RemoveUser_Call) RunAndReturn(run func(ctx context.Context, userID string, roomID string) error) *MockRoomRepository_RemoveUser_Call {
	_c.Call.Return(run)
	return _c
}
