// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"presence_service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPresence creates a new instance of MockPresence. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPresence(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPresence {
	mock := &MockPresence{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPresence is an autogenerated mock type for the Presence type
type MockPresence struct {
	mock.Mock
}

type MockPresence_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPresence) EXPECT() *MockPresence_Expecter {
	return &MockPresence_Expecter{mock: &_m.Mock}
}

// GetBulkStatus provides a mock function for the type MockPresence
func (_mock *MockPresence) GetBulkStatus(ctx context.Context, userIDs []string) ([]*domain.UserStatus, error) {
	ret := _mock.Called(ctx, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetBulkStatus")
	}

	var r0 []*domain.UserStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]*domain.UserStatus, error)); ok {
		return returnFunc(ctx, userIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []*domain.UserStatus); ok {
		r0 = returnFunc(ctx, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, userIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPresence_GetBulkStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBulkStatus'
type MockPresence_GetBulkStatus_Call struct {
	*mock.Call
}

// GetBulkStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDs []string
func (_e *MockPresence_Expecter) GetBulkStatus(ctx interface{}, userIDs interface{}) *MockPresence_GetBulkStatus_Call {
	return &MockPresence_GetBulkStatus_Call{Call: _e.mock.On("GetBulkStatus", ctx, userIDs)}
}

func (_c *MockPresence_GetBulkStatus_Call) Run(run func(ctx context.Context, userIDs []string)) *MockPresence_GetBulkStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPresence_GetBulkStatus_Call) Return(userStatuss []*domain.UserStatus, err error) *MockPresence_GetBulkStatus_Call {
	_c.Call.Return(userStatuss, err)
	return _c
}

func (_c *MockPresence_GetBulkStatus_Call) RunAndReturn(run func(ctx context.Context, userIDs []string) ([]*domain.UserStatus, error)) *MockPresence_GetBulkStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function for the type MockPresence
func (_mock *MockPresence) GetStatus(ctx context.Context, userID string) (map[string]string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPresence_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockPresence_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPresence_Expecter) GetStatus(ctx interface{}, userID interface{}) *MockPresence_GetStatus_Call {
	return &MockPresence_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx, userID)}
}

func (_c *MockPresence_GetStatus_Call) Run(run func(ctx context.Context, userID string)) *MockPresence_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPresence_GetStatus_Call) Return(stringToString map[string]string, err error) *MockPresence_GetStatus_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockPresence_GetStatus_Call) RunAndReturn(run func(ctx context.Context, userID string) (map[string]string, error)) *MockPresence_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Heartbeat provides a mock function for the type MockPresence
func (_mock *MockPresence) Heartbeat(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Heartbeat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPresence_Heartbeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Heartbeat'
type MockPresence_Heartbeat_Call struct {
	*mock.Call
}

// Heartbeat is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPresence_Expecter) Heartbeat(ctx interface{}, userID interface{}) *MockPresence_Heartbeat_Call {
	return &MockPresence_Heartbeat_Call{Call: _e.mock.On("Heartbeat", ctx, userID)}
}

func (_c *MockPresence_Heartbeat_Call) Run(run func(ctx context.Context, userID string)) *MockPresence_Heartbeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPresence_Heartbeat_Call) Return(err error) *MockPresence_Heartbeat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPresence_Heartbeat_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockPresence_Heartbeat_Call {
	_c.Call.Return(run)
	return _c
}

// MarkOnline provides a mock function for the type MockPresence
func (_mock *MockPresence) MarkOnline(ctx context.Context, userID string, metadata map[string]string) error {
	ret := _mock.Called(ctx, userID, metadata)

	if len(ret) == 0 {
		panic("no return value specified for MarkOnline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) error); ok {
		r0 = returnFunc(ctx, userID, metadata)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPresence_MarkOnline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOnline'
type MockPresence_MarkOnline_Call struct {
	*mock.Call
}

// MarkOnline is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - metadata map[string]string
func (_e *MockPresence_Expecter) MarkOnline(ctx interface{}, userID interface{}, metadata interface{}) *MockPresence_MarkOnline_Call {
	return &MockPresence_MarkOnline_Call{Call: _e.mock.On("MarkOnline", ctx, userID, metadata)}
}

func (_c *MockPresence_MarkOnline_Call) Run(run func(ctx context.Context, userID string, metadata map[string]string)) *MockPresence_MarkOnline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPresence_MarkOnline_Call) Return(err error) *MockPresence_MarkOnline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPresence_MarkOnline_Call) RunAndReturn(run func(ctx context.Context, userID string, metadata map[string]string) error) *MockPresence_MarkOnline_Call {
	_c.Call.Return(run)
	return _c
}
