// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPresenceRepository creates a new instance of MockPresenceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPresenceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPresenceRepository {
	mock := &MockPresenceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPresenceRepository is an autogenerated mock type for the PresenceRepository type
type MockPresenceRepository struct {
	mock.Mock
}

type MockPresenceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPresenceRepository) EXPECT() *MockPresenceRepository_Expecter {
	return &MockPresenceRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockPresenceRepository
func (_mock *MockPresenceRepository) Add(ctx context.Context, key string, metadata map[string]string) error {
	ret := _mock.Called(ctx, key, metadata)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string) error); ok {
		r0 = returnFunc(ctx, key, metadata)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPresenceRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockPresenceRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - metadata map[string]string
func (_e *MockPresenceRepository_Expecter) Add(ctx interface{}, key interface{}, metadata interface{}) *MockPresenceRepository_Add_Call {
	return &MockPresenceRepository_Add_Call{Call: _e.mock.On("Add", ctx, key, metadata)}
}

func (_c *MockPresenceRepository_Add_Call) Run(run func(ctx context.Context, key string, metadata map[string]string)) *MockPresenceRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPresenceRepository_Add_Call) Return(err error) *MockPresenceRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPresenceRepository_Add_Call) RunAndReturn(run func(ctx context.Context, key string, metadata map[string]string) error) *MockPresenceRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockPresenceRepository
func (_mock *MockPresenceRepository) Get(ctx context.Context, key string) (map[string]string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPresenceRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPresenceRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockPresenceRepository_Expecter) Get(ctx interface{}, key interface{}) *MockPresenceRepository_Get_Call {
	return &MockPresenceRepository_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockPresenceRepository_Get_Call) Run(run func(ctx context.Context, key string)) *MockPresenceRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPresenceRepository_Get_Call) Return(stringToString map[string]string, err error) *MockPresenceRepository_Get_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockPresenceRepository_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (map[string]string, error)) *MockPresenceRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetBulk provides a mock function for the type MockPresenceRepository
func (_mock *MockPresenceRepository) GetBulk(ctx context.Context, keys []string) ([]*redis.MapStringStringCmd, error) {
	ret := _mock.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for GetBulk")
	}

	var r0 []*redis.MapStringStringCmd
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]*redis.MapStringStringCmd, error)); ok {
		return returnFunc(ctx, keys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []*redis.MapStringStringCmd); ok {
		r0 = returnFunc(ctx, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*redis.MapStringStringCmd)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, keys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPresenceRepository_GetBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBulk'
type MockPresenceRepository_GetBulk_Call struct {
	*mock.Call
}

// GetBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *MockPresenceRepository_Expecter) GetBulk(ctx interface{}, keys interface{}) *MockPresenceRepository_GetBulk_Call {
	return &MockPresenceRepository_GetBulk_Call{Call: _e.mock.On("GetBulk", ctx, keys)}
}

func (_c *MockPresenceRepository_GetBulk_Call) Run(run func(ctx context.Context, keys []string)) *MockPresenceRepository_GetBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPresenceRepository_GetBulk_Call) Return(mapStringStringCmds []*redis.MapStringStringCmd, err error) *MockPresenceRepository_GetBulk_Call {
	_c.Call.Return(mapStringStringCmds, err)
	return _c
}

func (_c *MockPresenceRepository_GetBulk_Call) RunAndReturn(run func(ctx context.Context, keys []string) ([]*redis.MapStringStringCmd, error)) *MockPresenceRepository_GetBulk_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockPresenceRepository
func (_mock *MockPresenceRepository) Update(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPresenceRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPresenceRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockPresenceRepository_Expecter) Update(ctx interface{}, key interface{}) *MockPresenceRepository_Update_Call {
	return &MockPresenceRepository_Update_Call{Call: _e.mock.On("Update", ctx, key)}
}

func (_c *MockPresenceRepository_Update_Call) Run(run func(ctx context.Context, key string)) *MockPresenceRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPresenceRepository_Update_Call) Return(b bool, err error) *MockPresenceRepository_Update_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPresenceRepository_Update_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *MockPresenceRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
