// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"auth_service/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuth creates a new instance of MockAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuth {
	mock := &MockAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuth is an autogenerated mock type for the Auth type
type MockAuth struct {
	mock.Mock
}

type MockAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuth) EXPECT() *MockAuth_Expecter {
	return &MockAuth_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuth
func (_mock *MockAuth) Login(ctx context.Context, email string, password string) (*domain.AuthSession, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.AuthSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.AuthSession, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.AuthSession); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuth_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuth_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAuth_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *MockAuth_Login_Call {
	return &MockAuth_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockAuth_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockAuth_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuth_Login_Call) Return(authSession *domain.AuthSession, err error) *MockAuth_Login_Call {
	_c.Call.Return(authSession, err)
	return _c
}

func (_c *MockAuth_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*domain.AuthSession, error)) *MockAuth_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuth
func (_mock *MockAuth) Logout(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuth_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuth_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuth_Expecter) Logout(ctx interface{}, token interface{}) *MockAuth_Logout_Call {
	return &MockAuth_Logout_Call{Call: _e.mock.On("Logout", ctx, token)}
}

func (_c *MockAuth_Logout_Call) Run(run func(ctx context.Context, token string)) *MockAuth_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuth_Logout_Call) Return(err error) *MockAuth_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuth_Logout_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockAuth_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockAuth
func (_mock *MockAuth) Refresh(ctx context.Context, token string) (*domain.AuthSession, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *domain.AuthSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.AuthSession, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.AuthSession); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuth_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockAuth_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuth_Expecter) Refresh(ctx interface{}, token interface{}) *MockAuth_Refresh_Call {
	return &MockAuth_Refresh_Call{Call: _e.mock.On("Refresh", ctx, token)}
}

func (_c *MockAuth_Refresh_Call) Run(run func(ctx context.Context, token string)) *MockAuth_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuth_Refresh_Call) Return(authSession *domain.AuthSession, err error) *MockAuth_Refresh_Call {
	_c.Call.Return(authSession, err)
	return _c
}

func (_c *MockAuth_Refresh_Call) RunAndReturn(run func(ctx context.Context, token string) (*domain.AuthSession, error)) *MockAuth_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuth
func (_mock *MockAuth) Register(ctx context.Context, name string, email string, password string) (*domain.User, error) {
	ret := _mock.Called(ctx, name, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.User, error)); ok {
		return returnFunc(ctx, name, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.User); ok {
		r0 = returnFunc(ctx, name, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, name, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuth_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuth_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - email string
//   - password string
func (_e *MockAuth_Expecter) Register(ctx interface{}, name interface{}, email interface{}, password interface{}) *MockAuth_Register_Call {
	return &MockAuth_Register_Call{Call: _e.mock.On("Register", ctx, name, email, password)}
}

func (_c *MockAuth_Register_Call) Run(run func(ctx context.Context, name string, email string, password string)) *MockAuth_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuth_Register_Call) Return(user *domain.User, err error) *MockAuth_Register_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuth_Register_Call) RunAndReturn(run func(ctx context.Context, name string, email string, password string) (*domain.User, error)) *MockAuth_Register_Call {
	_c.Call.Return(run)
	return _c
}
