// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/friendship.proto

package friendspb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_FRIEND_REQUEST_UNSPECIFIED Status = 0
	Status_FRIEND_REQUEST_PENDING     Status = 1
	Status_FRIEND_REQUEST_CANCELLED   Status = 2
	Status_FRIEND_REQUEST_ACCEPTED    Status = 3
	Status_FRIEND_REQUEST_REJECTED    Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "FRIEND_REQUEST_UNSPECIFIED",
		1: "FRIEND_REQUEST_PENDING",
		2: "FRIEND_REQUEST_CANCELLED",
		3: "FRIEND_REQUEST_ACCEPTED",
		4: "FRIEND_REQUEST_REJECTED",
	}
	Status_value = map[string]int32{
		"FRIEND_REQUEST_UNSPECIFIED": 0,
		"FRIEND_REQUEST_PENDING":     1,
		"FRIEND_REQUEST_CANCELLED":   2,
		"FRIEND_REQUEST_ACCEPTED":    3,
		"FRIEND_REQUEST_REJECTED":    4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_friendship_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_friendship_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_friendship_proto_rawDescGZIP(), []int{0}
}

type IsFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFriendResponse) Reset() {
	*x = IsFriendResponse{}
	mi := &file_proto_friendship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFriendResponse) ProtoMessage() {}

func (x *IsFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friendship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFriendResponse.ProtoReflect.Descriptor instead.
func (*IsFriendResponse) Descriptor() ([]byte, []int) {
	return file_proto_friendship_proto_rawDescGZIP(), []int{0}
}

func (x *IsFriendResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type IsFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FriendId      string                 `protobuf:"bytes,2,opt,name=friendId,proto3" json:"friendId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFriendRequest) Reset() {
	*x = IsFriendRequest{}
	mi := &file_proto_friendship_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFriendRequest) ProtoMessage() {}

func (x *IsFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friendship_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFriendRequest.ProtoReflect.Descriptor instead.
func (*IsFriendRequest) Descriptor() ([]byte, []int) {
	return file_proto_friendship_proto_rawDescGZIP(), []int{1}
}

func (x *IsFriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IsFriendRequest) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

var File_proto_friendship_proto protoreflect.FileDescriptor

const file_proto_friendship_proto_rawDesc = "" +
	"\n" +
	"\x16proto/friendship.proto\"*\n" +
	"\x10IsFriendResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"E\n" +
	"\x0fIsFriendRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bfriendId\x18\x02 \x01(\tR\bfriendId*\x9c\x01\n" +
	"\x06Status\x12\x1e\n" +
	"\x1aFRIEND_REQUEST_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FRIEND_REQUEST_PENDING\x10\x01\x12\x1c\n" +
	"\x18FRIEND_REQUEST_CANCELLED\x10\x02\x12\x1b\n" +
	"\x17FRIEND_REQUEST_ACCEPTED\x10\x03\x12\x1b\n" +
	"\x17FRIEND_REQUEST_REJECTED\x10\x042?\n" +
	"\n" +
	"Friendship\x121\n" +
	"\bIsFriend\x12\x10.IsFriendRequest\x1a\x11.IsFriendResponse\"\x00B\x17Z\x15friends_service/protob\x06proto3"

var (
	file_proto_friendship_proto_rawDescOnce sync.Once
	file_proto_friendship_proto_rawDescData []byte
)

func file_proto_friendship_proto_rawDescGZIP() []byte {
	file_proto_friendship_proto_rawDescOnce.Do(func() {
		file_proto_friendship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_friendship_proto_rawDesc), len(file_proto_friendship_proto_rawDesc)))
	})
	return file_proto_friendship_proto_rawDescData
}

var file_proto_friendship_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_friendship_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_friendship_proto_goTypes = []any{
	(Status)(0),              // 0: Status
	(*IsFriendResponse)(nil), // 1: IsFriendResponse
	(*IsFriendRequest)(nil),  // 2: IsFriendRequest
}
var file_proto_friendship_proto_depIdxs = []int32{
	2, // 0: Friendship.IsFriend:input_type -> IsFriendRequest
	1, // 1: Friendship.IsFriend:output_type -> IsFriendResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_friendship_proto_init() }
func file_proto_friendship_proto_init() {
	if File_proto_friendship_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_friendship_proto_rawDesc), len(file_proto_friendship_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_friendship_proto_goTypes,
		DependencyIndexes: file_proto_friendship_proto_depIdxs,
		EnumInfos:         file_proto_friendship_proto_enumTypes,
		MessageInfos:      file_proto_friendship_proto_msgTypes,
	}.Build()
	File_proto_friendship_proto = out.File
	file_proto_friendship_proto_goTypes = nil
	file_proto_friendship_proto_depIdxs = nil
}
