// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"sync"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUser creates a new instance of MockUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUser {
	mock := &MockUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUser is an autogenerated mock type for the User type
type MockUser struct {
	mock.Mock
}

type MockUser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUser) EXPECT() *MockUser_Expecter {
	return &MockUser_Expecter{mock: &_m.Mock}
}

// AddRoomSub provides a mock function for the type MockUser
func (_mock *MockUser) AddRoomSub(ctx context.Context, room string) {
	_mock.Called(ctx, room)
	return
}

// MockUser_AddRoomSub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRoomSub'
type MockUser_AddRoomSub_Call struct {
	*mock.Call
}

// AddRoomSub is a helper method to define mock.On call
//   - ctx context.Context
//   - room string
func (_e *MockUser_Expecter) AddRoomSub(ctx interface{}, room interface{}) *MockUser_AddRoomSub_Call {
	return &MockUser_AddRoomSub_Call{Call: _e.mock.On("AddRoomSub", ctx, room)}
}

func (_c *MockUser_AddRoomSub_Call) Run(run func(ctx context.Context, room string)) *MockUser_AddRoomSub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUser_AddRoomSub_Call) Return() *MockUser_AddRoomSub_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUser_AddRoomSub_Call) RunAndReturn(run func(ctx context.Context, room string)) *MockUser_AddRoomSub_Call {
	_c.Run(run)
	return _c
}

// ID provides a mock function for the type MockUser
func (_mock *MockUser) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUser_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockUser_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockUser_Expecter) ID() *MockUser_ID_Call {
	return &MockUser_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockUser_ID_Call) Run(run func()) *MockUser_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUser_ID_Call) Return(s string) *MockUser_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUser_ID_Call) RunAndReturn(run func() string) *MockUser_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Listen provides a mock function for the type MockUser
func (_mock *MockUser) Listen(ctx context.Context, wg *sync.WaitGroup) {
	_mock.Called(ctx, wg)
	return
}

// MockUser_Listen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Listen'
type MockUser_Listen_Call struct {
	*mock.Call
}

// Listen is a helper method to define mock.On call
//   - ctx context.Context
//   - wg *sync.WaitGroup
func (_e *MockUser_Expecter) Listen(ctx interface{}, wg interface{}) *MockUser_Listen_Call {
	return &MockUser_Listen_Call{Call: _e.mock.On("Listen", ctx, wg)}
}

func (_c *MockUser_Listen_Call) Run(run func(ctx context.Context, wg *sync.WaitGroup)) *MockUser_Listen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sync.WaitGroup
		if args[1] != nil {
			arg1 = args[1].(*sync.WaitGroup)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUser_Listen_Call) Return() *MockUser_Listen_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUser_Listen_Call) RunAndReturn(run func(ctx context.Context, wg *sync.WaitGroup)) *MockUser_Listen_Call {
	_c.Run(run)
	return _c
}

// Name provides a mock function for the type MockUser
func (_mock *MockUser) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUser_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockUser_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockUser_Expecter) Name() *MockUser_Name_Call {
	return &MockUser_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockUser_Name_Call) Run(run func()) *MockUser_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUser_Name_Call) Return(s string) *MockUser_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUser_Name_Call) RunAndReturn(run func() string) *MockUser_Name_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveRoomSub provides a mock function for the type MockUser
func (_mock *MockUser) RemoveRoomSub(ctx context.Context, room string) error {
	ret := _mock.Called(ctx, room)

	if len(ret) == 0 {
		panic("no return value specified for RemoveRoomSub")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, room)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUser_RemoveRoomSub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRoomSub'
type MockUser_RemoveRoomSub_Call struct {
	*mock.Call
}

// RemoveRoomSub is a helper method to define mock.On call
//   - ctx context.Context
//   - room string
func (_e *MockUser_Expecter) RemoveRoomSub(ctx interface{}, room interface{}) *MockUser_RemoveRoomSub_Call {
	return &MockUser_RemoveRoomSub_Call{Call: _e.mock.On("RemoveRoomSub", ctx, room)}
}

func (_c *MockUser_RemoveRoomSub_Call) Run(run func(ctx context.Context, room string)) *MockUser_RemoveRoomSub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUser_RemoveRoomSub_Call) Return(err error) *MockUser_RemoveRoomSub_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUser_RemoveRoomSub_Call) RunAndReturn(run func(ctx context.Context, room string) error) *MockUser_RemoveRoomSub_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockUser
func (_mock *MockUser) Stop() {
	_mock.Called()
	return
}

// MockUser_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockUser_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockUser_Expecter) Stop() *MockUser_Stop_Call {
	return &MockUser_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockUser_Stop_Call) Run(run func()) *MockUser_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUser_Stop_Call) Return() *MockUser_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUser_Stop_Call) RunAndReturn(run func()) *MockUser_Stop_Call {
	_c.Run(run)
	return _c
}
