// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"chat_service/internal/domain"
	"context"
	"sync"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUser creates a new instance of MockUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUser {
	mock := &MockUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUser is an autogenerated mock type for the User type
type MockUser struct {
	mock.Mock
}

type MockUser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUser) EXPECT() *MockUser_Expecter {
	return &MockUser_Expecter{mock: &_m.Mock}
}

// AddRoom provides a mock function for the type MockUser
func (_mock *MockUser) AddRoom(room Room) error {
	ret := _mock.Called(room)

	if len(ret) == 0 {
		panic("no return value specified for AddRoom")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Room) error); ok {
		r0 = returnFunc(room)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUser_AddRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRoom'
type MockUser_AddRoom_Call struct {
	*mock.Call
}

// AddRoom is a helper method to define mock.On call
//   - room Room
func (_e *MockUser_Expecter) AddRoom(room interface{}) *MockUser_AddRoom_Call {
	return &MockUser_AddRoom_Call{Call: _e.mock.On("AddRoom", room)}
}

func (_c *MockUser_AddRoom_Call) Run(run func(room Room)) *MockUser_AddRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Room
		if args[0] != nil {
			arg0 = args[0].(Room)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUser_AddRoom_Call) Return(err error) *MockUser_AddRoom_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUser_AddRoom_Call) RunAndReturn(run func(room Room) error) *MockUser_AddRoom_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRoom provides a mock function for the type MockUser
func (_mock *MockUser) DeleteRoom(room Room) error {
	ret := _mock.Called(room)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoom")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Room) error); ok {
		r0 = returnFunc(room)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUser_DeleteRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRoom'
type MockUser_DeleteRoom_Call struct {
	*mock.Call
}

// DeleteRoom is a helper method to define mock.On call
//   - room Room
func (_e *MockUser_Expecter) DeleteRoom(room interface{}) *MockUser_DeleteRoom_Call {
	return &MockUser_DeleteRoom_Call{Call: _e.mock.On("DeleteRoom", room)}
}

func (_c *MockUser_DeleteRoom_Call) Run(run func(room Room)) *MockUser_DeleteRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Room
		if args[0] != nil {
			arg0 = args[0].(Room)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUser_DeleteRoom_Call) Return(err error) *MockUser_DeleteRoom_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUser_DeleteRoom_Call) RunAndReturn(run func(room Room) error) *MockUser_DeleteRoom_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockUser
func (_mock *MockUser) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUser_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockUser_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockUser_Expecter) ID() *MockUser_ID_Call {
	return &MockUser_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockUser_ID_Call) Run(run func()) *MockUser_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUser_ID_Call) Return(s string) *MockUser_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUser_ID_Call) RunAndReturn(run func() string) *MockUser_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Listen provides a mock function for the type MockUser
func (_mock *MockUser) Listen(ctx context.Context, wg *sync.WaitGroup) {
	_mock.Called(ctx, wg)
	return
}

// MockUser_Listen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Listen'
type MockUser_Listen_Call struct {
	*mock.Call
}

// Listen is a helper method to define mock.On call
//   - ctx context.Context
//   - wg *sync.WaitGroup
func (_e *MockUser_Expecter) Listen(ctx interface{}, wg interface{}) *MockUser_Listen_Call {
	return &MockUser_Listen_Call{Call: _e.mock.On("Listen", ctx, wg)}
}

func (_c *MockUser_Listen_Call) Run(run func(ctx context.Context, wg *sync.WaitGroup)) *MockUser_Listen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sync.WaitGroup
		if args[1] != nil {
			arg1 = args[1].(*sync.WaitGroup)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUser_Listen_Call) Return() *MockUser_Listen_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUser_Listen_Call) RunAndReturn(run func(ctx context.Context, wg *sync.WaitGroup)) *MockUser_Listen_Call {
	_c.Run(run)
	return _c
}

// Name provides a mock function for the type MockUser
func (_mock *MockUser) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUser_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockUser_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockUser_Expecter) Name() *MockUser_Name_Call {
	return &MockUser_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockUser_Name_Call) Run(run func()) *MockUser_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUser_Name_Call) Return(s string) *MockUser_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUser_Name_Call) RunAndReturn(run func() string) *MockUser_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Rooms provides a mock function for the type MockUser
func (_mock *MockUser) Rooms() map[string]Room {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rooms")
	}

	var r0 map[string]Room
	if returnFunc, ok := ret.Get(0).(func() map[string]Room); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]Room)
		}
	}
	return r0
}

// MockUser_Rooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rooms'
type MockUser_Rooms_Call struct {
	*mock.Call
}

// Rooms is a helper method to define mock.On call
func (_e *MockUser_Expecter) Rooms() *MockUser_Rooms_Call {
	return &MockUser_Rooms_Call{Call: _e.mock.On("Rooms")}
}

func (_c *MockUser_Rooms_Call) Run(run func()) *MockUser_Rooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUser_Rooms_Call) Return(stringToRoom map[string]Room) *MockUser_Rooms_Call {
	_c.Call.Return(stringToRoom)
	return _c
}

func (_c *MockUser_Rooms_Call) RunAndReturn(run func() map[string]Room) *MockUser_Rooms_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockUser
func (_mock *MockUser) Stop() {
	_mock.Called()
	return
}

// MockUser_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockUser_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockUser_Expecter) Stop() *MockUser_Stop_Call {
	return &MockUser_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockUser_Stop_Call) Run(run func()) *MockUser_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUser_Stop_Call) Return() *MockUser_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUser_Stop_Call) RunAndReturn(run func()) *MockUser_Stop_Call {
	_c.Run(run)
	return _c
}

// Write provides a mock function for the type MockUser
func (_mock *MockUser) Write(ctx context.Context, msg *domain.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUser_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockUser_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *domain.Message
func (_e *MockUser_Expecter) Write(ctx interface{}, msg interface{}) *MockUser_Write_Call {
	return &MockUser_Write_Call{Call: _e.mock.On("Write", ctx, msg)}
}

func (_c *MockUser_Write_Call) Run(run func(ctx context.Context, msg *domain.Message)) *MockUser_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Message
		if args[1] != nil {
			arg1 = args[1].(*domain.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUser_Write_Call) Return(err error) *MockUser_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUser_Write_Call) RunAndReturn(run func(ctx context.Context, msg *domain.Message) error) *MockUser_Write_Call {
	_c.Call.Return(run)
	return _c
}
