// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"chat_service/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRoom creates a new instance of MockRoom. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoom(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoom {
	mock := &MockRoom{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoom is an autogenerated mock type for the Room type
type MockRoom struct {
	mock.Mock
}

type MockRoom_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoom) EXPECT() *MockRoom_Expecter {
	return &MockRoom_Expecter{mock: &_m.Mock}
}

// AddUser provides a mock function for the type MockRoom
func (_mock *MockRoom) AddUser(user User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoom_AddUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUser'
type MockRoom_AddUser_Call struct {
	*mock.Call
}

// AddUser is a helper method to define mock.On call
//   - user User
func (_e *MockRoom_Expecter) AddUser(user interface{}) *MockRoom_AddUser_Call {
	return &MockRoom_AddUser_Call{Call: _e.mock.On("AddUser", user)}
}

func (_c *MockRoom_AddUser_Call) Run(run func(user User)) *MockRoom_AddUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 User
		if args[0] != nil {
			arg0 = args[0].(User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoom_AddUser_Call) Return(err error) *MockRoom_AddUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoom_AddUser_Call) RunAndReturn(run func(user User) error) *MockRoom_AddUser_Call {
	_c.Call.Return(run)
	return _c
}

// Broadcast provides a mock function for the type MockRoom
func (_mock *MockRoom) Broadcast(ctx context.Context, msg *domain.Message) {
	_mock.Called(ctx, msg)
	return
}

// MockRoom_Broadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Broadcast'
type MockRoom_Broadcast_Call struct {
	*mock.Call
}

// Broadcast is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *domain.Message
func (_e *MockRoom_Expecter) Broadcast(ctx interface{}, msg interface{}) *MockRoom_Broadcast_Call {
	return &MockRoom_Broadcast_Call{Call: _e.mock.On("Broadcast", ctx, msg)}
}

func (_c *MockRoom_Broadcast_Call) Run(run func(ctx context.Context, msg *domain.Message)) *MockRoom_Broadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Message
		if args[1] != nil {
			arg1 = args[1].(*domain.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoom_Broadcast_Call) Return() *MockRoom_Broadcast_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRoom_Broadcast_Call) RunAndReturn(run func(ctx context.Context, msg *domain.Message)) *MockRoom_Broadcast_Call {
	_c.Run(run)
	return _c
}

// GetUsernames provides a mock function for the type MockRoom
func (_mock *MockRoom) GetUsernames() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUsernames")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockRoom_GetUsernames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsernames'
type MockRoom_GetUsernames_Call struct {
	*mock.Call
}

// GetUsernames is a helper method to define mock.On call
func (_e *MockRoom_Expecter) GetUsernames() *MockRoom_GetUsernames_Call {
	return &MockRoom_GetUsernames_Call{Call: _e.mock.On("GetUsernames")}
}

func (_c *MockRoom_GetUsernames_Call) Run(run func()) *MockRoom_GetUsernames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRoom_GetUsernames_Call) Return(strings []string) *MockRoom_GetUsernames_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockRoom_GetUsernames_Call) RunAndReturn(run func() []string) *MockRoom_GetUsernames_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockRoom
func (_mock *MockRoom) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRoom_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockRoom_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockRoom_Expecter) ID() *MockRoom_ID_Call {
	return &MockRoom_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockRoom_ID_Call) Run(run func()) *MockRoom_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRoom_ID_Call) Return(s string) *MockRoom_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRoom_ID_Call) RunAndReturn(run func() string) *MockRoom_ID_Call {
	_c.Call.Return(run)
	return _c
}

// IsEmpty provides a mock function for the type MockRoom
func (_mock *MockRoom) IsEmpty() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEmpty")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRoom_IsEmpty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEmpty'
type MockRoom_IsEmpty_Call struct {
	*mock.Call
}

// IsEmpty is a helper method to define mock.On call
func (_e *MockRoom_Expecter) IsEmpty() *MockRoom_IsEmpty_Call {
	return &MockRoom_IsEmpty_Call{Call: _e.mock.On("IsEmpty")}
}

func (_c *MockRoom_IsEmpty_Call) Run(run func()) *MockRoom_IsEmpty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRoom_IsEmpty_Call) Return(b bool) *MockRoom_IsEmpty_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRoom_IsEmpty_Call) RunAndReturn(run func() bool) *MockRoom_IsEmpty_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUser provides a mock function for the type MockRoom
func (_mock *MockRoom) RemoveUser(user User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoom_RemoveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUser'
type MockRoom_RemoveUser_Call struct {
	*mock.Call
}

// RemoveUser is a helper method to define mock.On call
//   - user User
func (_e *MockRoom_Expecter) RemoveUser(user interface{}) *MockRoom_RemoveUser_Call {
	return &MockRoom_RemoveUser_Call{Call: _e.mock.On("RemoveUser", user)}
}

func (_c *MockRoom_RemoveUser_Call) Run(run func(user User)) *MockRoom_RemoveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 User
		if args[0] != nil {
			arg0 = args[0].(User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoom_RemoveUser_Call) Return(err error) *MockRoom_RemoveUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoom_RemoveUser_Call) RunAndReturn(run func(user User) error) *MockRoom_RemoveUser_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockRoom
func (_mock *MockRoom) Run(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockRoom_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockRoom_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoom_Expecter) Run(ctx interface{}) *MockRoom_Run_Call {
	return &MockRoom_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *MockRoom_Run_Call) Run(run func(ctx context.Context)) *MockRoom_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoom_Run_Call) Return() *MockRoom_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRoom_Run_Call) RunAndReturn(run func(ctx context.Context)) *MockRoom_Run_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockRoom
func (_mock *MockRoom) Stop() {
	_mock.Called()
	return
}

// MockRoom_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockRoom_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockRoom_Expecter) Stop() *MockRoom_Stop_Call {
	return &MockRoom_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockRoom_Stop_Call) Run(run func()) *MockRoom_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRoom_Stop_Call) Return() *MockRoom_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRoom_Stop_Call) RunAndReturn(run func()) *MockRoom_Stop_Call {
	_c.Run(run)
	return _c
}
