// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"chat_service/internal/domain"
	"context"
	"time"

	"github.com/gorilla/websocket"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHub creates a new instance of MockHub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHub {
	mock := &MockHub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHub is an autogenerated mock type for the Hub type
type MockHub struct {
	mock.Mock
}

type MockHub_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHub) EXPECT() *MockHub_Expecter {
	return &MockHub_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type MockHub
func (_mock *MockHub) Connect(ctx context.Context, userID string, conn *websocket.Conn) error {
	ret := _mock.Called(ctx, userID, conn)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *websocket.Conn) error); ok {
		r0 = returnFunc(ctx, userID, conn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHub_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockHub_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - conn *websocket.Conn
func (_e *MockHub_Expecter) Connect(ctx interface{}, userID interface{}, conn interface{}) *MockHub_Connect_Call {
	return &MockHub_Connect_Call{Call: _e.mock.On("Connect", ctx, userID, conn)}
}

func (_c *MockHub_Connect_Call) Run(run func(ctx context.Context, userID string, conn *websocket.Conn)) *MockHub_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *websocket.Conn
		if args[2] != nil {
			arg2 = args[2].(*websocket.Conn)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHub_Connect_Call) Return(err error) *MockHub_Connect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHub_Connect_Call) RunAndReturn(run func(ctx context.Context, userID string, conn *websocket.Conn) error) *MockHub_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRoom provides a mock function for the type MockHub
func (_mock *MockHub) CreateRoom(ctx context.Context, roomName string, userID string) (*domain.Room, error) {
	ret := _mock.Called(ctx, roomName, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 *domain.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Room, error)); ok {
		return returnFunc(ctx, roomName, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.Room); ok {
		r0 = returnFunc(ctx, roomName, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, roomName, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHub_CreateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoom'
type MockHub_CreateRoom_Call struct {
	*mock.Call
}

// CreateRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomName string
//   - userID string
func (_e *MockHub_Expecter) CreateRoom(ctx interface{}, roomName interface{}, userID interface{}) *MockHub_CreateRoom_Call {
	return &MockHub_CreateRoom_Call{Call: _e.mock.On("CreateRoom", ctx, roomName, userID)}
}

func (_c *MockHub_CreateRoom_Call) Run(run func(ctx context.Context, roomName string, userID string)) *MockHub_CreateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHub_CreateRoom_Call) Return(room *domain.Room, err error) *MockHub_CreateRoom_Call {
	_c.Call.Return(room, err)
	return _c
}

func (_c *MockHub_CreateRoom_Call) RunAndReturn(run func(ctx context.Context, roomName string, userID string) (*domain.Room, error)) *MockHub_CreateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function for the type MockHub
func (_mock *MockHub) Disconnect(ctx context.Context, userID string) (User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHub_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockHub_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockHub_Expecter) Disconnect(ctx interface{}, userID interface{}) *MockHub_Disconnect_Call {
	return &MockHub_Disconnect_Call{Call: _e.mock.On("Disconnect", ctx, userID)}
}

func (_c *MockHub_Disconnect_Call) Run(run func(ctx context.Context, userID string)) *MockHub_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHub_Disconnect_Call) Return(user User, err error) *MockHub_Disconnect_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockHub_Disconnect_Call) RunAndReturn(run func(ctx context.Context, userID string) (User, error)) *MockHub_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoomClients provides a mock function for the type MockHub
func (_mock *MockHub) GetRoomClients(ctx context.Context, roomID string) ([]*domain.User, error) {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomClients")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.User, error)); ok {
		return returnFunc(ctx, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.User); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHub_GetRoomClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoomClients'
type MockHub_GetRoomClients_Call struct {
	*mock.Call
}

// GetRoomClients is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockHub_Expecter) GetRoomClients(ctx interface{}, roomID interface{}) *MockHub_GetRoomClients_Call {
	return &MockHub_GetRoomClients_Call{Call: _e.mock.On("GetRoomClients", ctx, roomID)}
}

func (_c *MockHub_GetRoomClients_Call) Run(run func(ctx context.Context, roomID string)) *MockHub_GetRoomClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHub_GetRoomClients_Call) Return(users []*domain.User, err error) *MockHub_GetRoomClients_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockHub_GetRoomClients_Call) RunAndReturn(run func(ctx context.Context, roomID string) ([]*domain.User, error)) *MockHub_GetRoomClients_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoomHistory provides a mock function for the type MockHub
func (_mock *MockHub) GetRoomHistory(ctx context.Context, userID string, roomID string, before time.Time) ([]*domain.Message, error) {
	ret := _mock.Called(ctx, userID, roomID, before)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomHistory")
	}

	var r0 []*domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) ([]*domain.Message, error)); ok {
		return returnFunc(ctx, userID, roomID, before)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) []*domain.Message); ok {
		r0 = returnFunc(ctx, userID, roomID, before)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, roomID, before)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHub_GetRoomHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoomHistory'
type MockHub_GetRoomHistory_Call struct {
	*mock.Call
}

// GetRoomHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - roomID string
//   - before time.Time
func (_e *MockHub_Expecter) GetRoomHistory(ctx interface{}, userID interface{}, roomID interface{}, before interface{}) *MockHub_GetRoomHistory_Call {
	return &MockHub_GetRoomHistory_Call{Call: _e.mock.On("GetRoomHistory", ctx, userID, roomID, before)}
}

func (_c *MockHub_GetRoomHistory_Call) Run(run func(ctx context.Context, userID string, roomID string, before time.Time)) *MockHub_GetRoomHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHub_GetRoomHistory_Call) Return(messages []*domain.Message, err error) *MockHub_GetRoomHistory_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockHub_GetRoomHistory_Call) RunAndReturn(run func(ctx context.Context, userID string, roomID string, before time.Time) ([]*domain.Message, error)) *MockHub_GetRoomHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoomsByUser provides a mock function for the type MockHub
func (_mock *MockHub) GetRoomsByUser(ctx context.Context, userID string) ([]*domain.Room, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomsByUser")
	}

	var r0 []*domain.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Room, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Room); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHub_GetRoomsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoomsByUser'
type MockHub_GetRoomsByUser_Call struct {
	*mock.Call
}

// GetRoomsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockHub_Expecter) GetRoomsByUser(ctx interface{}, userID interface{}) *MockHub_GetRoomsByUser_Call {
	return &MockHub_GetRoomsByUser_Call{Call: _e.mock.On("GetRoomsByUser", ctx, userID)}
}

func (_c *MockHub_GetRoomsByUser_Call) Run(run func(ctx context.Context, userID string)) *MockHub_GetRoomsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHub_GetRoomsByUser_Call) Return(rooms []*domain.Room, err error) *MockHub_GetRoomsByUser_Call {
	_c.Call.Return(rooms, err)
	return _c
}

func (_c *MockHub_GetRoomsByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*domain.Room, error)) *MockHub_GetRoomsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// InviteUser provides a mock function for the type MockHub
func (_mock *MockHub) InviteUser(ctx context.Context, inviterID string, inviteeID string, roomID string) error {
	ret := _mock.Called(ctx, inviterID, inviteeID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for InviteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, inviterID, inviteeID, roomID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHub_InviteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InviteUser'
type MockHub_InviteUser_Call struct {
	*mock.Call
}

// InviteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - inviterID string
//   - inviteeID string
//   - roomID string
func (_e *MockHub_Expecter) InviteUser(ctx interface{}, inviterID interface{}, inviteeID interface{}, roomID interface{}) *MockHub_InviteUser_Call {
	return &MockHub_InviteUser_Call{Call: _e.mock.On("InviteUser", ctx, inviterID, inviteeID, roomID)}
}

func (_c *MockHub_InviteUser_Call) Run(run func(ctx context.Context, inviterID string, inviteeID string, roomID string)) *MockHub_InviteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHub_InviteUser_Call) Return(err error) *MockHub_InviteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHub_InviteUser_Call) RunAndReturn(run func(ctx context.Context, inviterID string, inviteeID string, roomID string) error) *MockHub_InviteUser_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveRoom provides a mock function for the type MockHub
func (_mock *MockHub) LeaveRoom(ctx context.Context, userID string, roomID string) error {
	ret := _mock.Called(ctx, userID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for LeaveRoom")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, roomID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHub_LeaveRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveRoom'
type MockHub_LeaveRoom_Call struct {
	*mock.Call
}

// LeaveRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - roomID string
func (_e *MockHub_Expecter) LeaveRoom(ctx interface{}, userID interface{}, roomID interface{}) *MockHub_LeaveRoom_Call {
	return &MockHub_LeaveRoom_Call{Call: _e.mock.On("LeaveRoom", ctx, userID, roomID)}
}

func (_c *MockHub_LeaveRoom_Call) Run(run func(ctx context.Context, userID string, roomID string)) *MockHub_LeaveRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHub_LeaveRoom_Call) Return(err error) *MockHub_LeaveRoom_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHub_LeaveRoom_Call) RunAndReturn(run func(ctx context.Context, userID string, roomID string) error) *MockHub_LeaveRoom_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockHub
func (_mock *MockHub) Shutdown(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockHub_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockHub_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHub_Expecter) Shutdown(ctx interface{}) *MockHub_Shutdown_Call {
	return &MockHub_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockHub_Shutdown_Call) Run(run func(ctx context.Context)) *MockHub_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHub_Shutdown_Call) Return() *MockHub_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHub_Shutdown_Call) RunAndReturn(run func(ctx context.Context)) *MockHub_Shutdown_Call {
	_c.Run(run)
	return _c
}
