env: local

http:
  port: 8082
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 10s

redis:
  addrs:
    - redis-local:6379

origin_whitelist:
  - "http://localhost:3000"

friends_grpc_addr: "friends-local:50051"