env: prod

http:
  port: 8082
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 10s

redis:
  addrs:
    - redis-prod:6379

origin_whitelist:
  - "http://localhost:8080"

friends_grpc_addr: "friends-prod:50051"