// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/friendship.proto

package friendspb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Friendship_IsFriend_FullMethodName = "/Friendship/IsFriend"
)

// FriendshipClient is the client API for Friendship service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FriendshipClient interface {
	IsFriend(ctx context.Context, in *IsFriendRequest, opts ...grpc.CallOption) (*IsFriendResponse, error)
}

type friendshipClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendshipClient(cc grpc.ClientConnInterface) FriendshipClient {
	return &friendshipClient{cc}
}

func (c *friendshipClient) IsFriend(ctx context.Context, in *IsFriendRequest, opts ...grpc.CallOption) (*IsFriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsFriendResponse)
	err := c.cc.Invoke(ctx, Friendship_IsFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendshipServer is the server API for Friendship service.
// All implementations must embed UnimplementedFriendshipServer
// for forward compatibility.
type FriendshipServer interface {
	IsFriend(context.Context, *IsFriendRequest) (*IsFriendResponse, error)
	mustEmbedUnimplementedFriendshipServer()
}

// UnimplementedFriendshipServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFriendshipServer struct{}

func (UnimplementedFriendshipServer) IsFriend(context.Context, *IsFriendRequest) (*IsFriendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsFriend not implemented")
}
func (UnimplementedFriendshipServer) mustEmbedUnimplementedFriendshipServer() {}
func (UnimplementedFriendshipServer) testEmbeddedByValue()                    {}

// UnsafeFriendshipServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendshipServer will
// result in compilation errors.
type UnsafeFriendshipServer interface {
	mustEmbedUnimplementedFriendshipServer()
}

func RegisterFriendshipServer(s grpc.ServiceRegistrar, srv FriendshipServer) {
	// If the following call panics, it indicates UnimplementedFriendshipServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Friendship_ServiceDesc, srv)
}

func _Friendship_IsFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendshipServer).IsFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friendship_IsFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendshipServer).IsFriend(ctx, req.(*IsFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Friendship_ServiceDesc is the grpc.ServiceDesc for Friendship service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Friendship_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Friendship",
	HandlerType: (*FriendshipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsFriend",
			Handler:    _Friendship_IsFriend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/friendship.proto",
}
