// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"friends_service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFriendshipRepository creates a new instance of MockFriendshipRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFriendshipRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFriendshipRepository {
	mock := &MockFriendshipRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFriendshipRepository is an autogenerated mock type for the FriendshipRepository type
type MockFriendshipRepository struct {
	mock.Mock
}

type MockFriendshipRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFriendshipRepository) EXPECT() *MockFriendshipRepository_Expecter {
	return &MockFriendshipRepository_Expecter{mock: &_m.Mock}
}

// AcceptFriend provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) AcceptFriend(ctx context.Context, userID string, inviterID string) (bool, error) {
	ret := _mock.Called(ctx, userID, inviterID)

	if len(ret) == 0 {
		panic("no return value specified for AcceptFriend")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, userID, inviterID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, userID, inviterID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, inviterID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_AcceptFriend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptFriend'
type MockFriendshipRepository_AcceptFriend_Call struct {
	*mock.Call
}

// AcceptFriend is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - inviterID string
func (_e *MockFriendshipRepository_Expecter) AcceptFriend(ctx interface{}, userID interface{}, inviterID interface{}) *MockFriendshipRepository_AcceptFriend_Call {
	return &MockFriendshipRepository_AcceptFriend_Call{Call: _e.mock.On("AcceptFriend", ctx, userID, inviterID)}
}

func (_c *MockFriendshipRepository_AcceptFriend_Call) Run(run func(ctx context.Context, userID string, inviterID string)) *MockFriendshipRepository_AcceptFriend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_AcceptFriend_Call) Return(b bool, err error) *MockFriendshipRepository_AcceptFriend_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFriendshipRepository_AcceptFriend_Call) RunAndReturn(run func(ctx context.Context, userID string, inviterID string) (bool, error)) *MockFriendshipRepository_AcceptFriend_Call {
	_c.Call.Return(run)
	return _c
}

// AddFriend provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) AddFriend(ctx context.Context, inviterID string, inviteeID string) error {
	ret := _mock.Called(ctx, inviterID, inviteeID)

	if len(ret) == 0 {
		panic("no return value specified for AddFriend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, inviterID, inviteeID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFriendshipRepository_AddFriend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFriend'
type MockFriendshipRepository_AddFriend_Call struct {
	*mock.Call
}

// AddFriend is a helper method to define mock.On call
//   - ctx context.Context
//   - inviterID string
//   - inviteeID string
func (_e *MockFriendshipRepository_Expecter) AddFriend(ctx interface{}, inviterID interface{}, inviteeID interface{}) *MockFriendshipRepository_AddFriend_Call {
	return &MockFriendshipRepository_AddFriend_Call{Call: _e.mock.On("AddFriend", ctx, inviterID, inviteeID)}
}

func (_c *MockFriendshipRepository_AddFriend_Call) Run(run func(ctx context.Context, inviterID string, inviteeID string)) *MockFriendshipRepository_AddFriend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_AddFriend_Call) Return(err error) *MockFriendshipRepository_AddFriend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFriendshipRepository_AddFriend_Call) RunAndReturn(run func(ctx context.Context, inviterID string, inviteeID string) error) *MockFriendshipRepository_AddFriend_Call {
	_c.Call.Return(run)
	return _c
}

// CancelFriend provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) CancelFriend(ctx context.Context, userID string, inviterID string) (bool, error) {
	ret := _mock.Called(ctx, userID, inviterID)

	if len(ret) == 0 {
		panic("no return value specified for CancelFriend")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, userID, inviterID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, userID, inviterID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, inviterID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_CancelFriend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelFriend'
type MockFriendshipRepository_CancelFriend_Call struct {
	*mock.Call
}

// CancelFriend is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - inviterID string
func (_e *MockFriendshipRepository_Expecter) CancelFriend(ctx interface{}, userID interface{}, inviterID interface{}) *MockFriendshipRepository_CancelFriend_Call {
	return &MockFriendshipRepository_CancelFriend_Call{Call: _e.mock.On("CancelFriend", ctx, userID, inviterID)}
}

func (_c *MockFriendshipRepository_CancelFriend_Call) Run(run func(ctx context.Context, userID string, inviterID string)) *MockFriendshipRepository_CancelFriend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_CancelFriend_Call) Return(b bool, err error) *MockFriendshipRepository_CancelFriend_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFriendshipRepository_CancelFriend_Call) RunAndReturn(run func(ctx context.Context, userID string, inviterID string) (bool, error)) *MockFriendshipRepository_CancelFriend_Call {
	_c.Call.Return(run)
	return _c
}

// DeclineFriend provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) DeclineFriend(ctx context.Context, userID string, inviterID string) (bool, error) {
	ret := _mock.Called(ctx, userID, inviterID)

	if len(ret) == 0 {
		panic("no return value specified for DeclineFriend")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, userID, inviterID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, userID, inviterID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, inviterID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_DeclineFriend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeclineFriend'
type MockFriendshipRepository_DeclineFriend_Call struct {
	*mock.Call
}

// DeclineFriend is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - inviterID string
func (_e *MockFriendshipRepository_Expecter) DeclineFriend(ctx interface{}, userID interface{}, inviterID interface{}) *MockFriendshipRepository_DeclineFriend_Call {
	return &MockFriendshipRepository_DeclineFriend_Call{Call: _e.mock.On("DeclineFriend", ctx, userID, inviterID)}
}

func (_c *MockFriendshipRepository_DeclineFriend_Call) Run(run func(ctx context.Context, userID string, inviterID string)) *MockFriendshipRepository_DeclineFriend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_DeclineFriend_Call) Return(b bool, err error) *MockFriendshipRepository_DeclineFriend_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFriendshipRepository_DeclineFriend_Call) RunAndReturn(run func(ctx context.Context, userID string, inviterID string) (bool, error)) *MockFriendshipRepository_DeclineFriend_Call {
	_c.Call.Return(run)
	return _c
}

// GetFriendByUsername provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) GetFriendByUsername(ctx context.Context, userID string, username string, cursor string) ([]*domain.User, error) {
	ret := _mock.Called(ctx, userID, username, cursor)

	if len(ret) == 0 {
		panic("no return value specified for GetFriendByUsername")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]*domain.User, error)); ok {
		return returnFunc(ctx, userID, username, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []*domain.User); ok {
		r0 = returnFunc(ctx, userID, username, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, username, cursor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_GetFriendByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFriendByUsername'
type MockFriendshipRepository_GetFriendByUsername_Call struct {
	*mock.Call
}

// GetFriendByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - username string
//   - cursor string
func (_e *MockFriendshipRepository_Expecter) GetFriendByUsername(ctx interface{}, userID interface{}, username interface{}, cursor interface{}) *MockFriendshipRepository_GetFriendByUsername_Call {
	return &MockFriendshipRepository_GetFriendByUsername_Call{Call: _e.mock.On("GetFriendByUsername", ctx, userID, username, cursor)}
}

func (_c *MockFriendshipRepository_GetFriendByUsername_Call) Run(run func(ctx context.Context, userID string, username string, cursor string)) *MockFriendshipRepository_GetFriendByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_GetFriendByUsername_Call) Return(users []*domain.User, err error) *MockFriendshipRepository_GetFriendByUsername_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockFriendshipRepository_GetFriendByUsername_Call) RunAndReturn(run func(ctx context.Context, userID string, username string, cursor string) ([]*domain.User, error)) *MockFriendshipRepository_GetFriendByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetFriends provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) GetFriends(ctx context.Context, userID string) ([]*domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFriends")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_GetFriends_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFriends'
type MockFriendshipRepository_GetFriends_Call struct {
	*mock.Call
}

// GetFriends is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockFriendshipRepository_Expecter) GetFriends(ctx interface{}, userID interface{}) *MockFriendshipRepository_GetFriends_Call {
	return &MockFriendshipRepository_GetFriends_Call{Call: _e.mock.On("GetFriends", ctx, userID)}
}

func (_c *MockFriendshipRepository_GetFriends_Call) Run(run func(ctx context.Context, userID string)) *MockFriendshipRepository_GetFriends_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_GetFriends_Call) Return(users []*domain.User, err error) *MockFriendshipRepository_GetFriends_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockFriendshipRepository_GetFriends_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*domain.User, error)) *MockFriendshipRepository_GetFriends_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvites provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) GetInvites(ctx context.Context, userID string) ([]*domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetInvites")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_GetInvites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvites'
type MockFriendshipRepository_GetInvites_Call struct {
	*mock.Call
}

// GetInvites is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockFriendshipRepository_Expecter) GetInvites(ctx interface{}, userID interface{}) *MockFriendshipRepository_GetInvites_Call {
	return &MockFriendshipRepository_GetInvites_Call{Call: _e.mock.On("GetInvites", ctx, userID)}
}

func (_c *MockFriendshipRepository_GetInvites_Call) Run(run func(ctx context.Context, userID string)) *MockFriendshipRepository_GetInvites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_GetInvites_Call) Return(users []*domain.User, err error) *MockFriendshipRepository_GetInvites_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockFriendshipRepository_GetInvites_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*domain.User, error)) *MockFriendshipRepository_GetInvites_Call {
	_c.Call.Return(run)
	return _c
}

// IsFriend provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) IsFriend(ctx context.Context, userID string, friendID string) (bool, error) {
	ret := _mock.Called(ctx, userID, friendID)

	if len(ret) == 0 {
		panic("no return value specified for IsFriend")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, userID, friendID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, userID, friendID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, friendID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_IsFriend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFriend'
type MockFriendshipRepository_IsFriend_Call struct {
	*mock.Call
}

// IsFriend is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - friendID string
func (_e *MockFriendshipRepository_Expecter) IsFriend(ctx interface{}, userID interface{}, friendID interface{}) *MockFriendshipRepository_IsFriend_Call {
	return &MockFriendshipRepository_IsFriend_Call{Call: _e.mock.On("IsFriend", ctx, userID, friendID)}
}

func (_c *MockFriendshipRepository_IsFriend_Call) Run(run func(ctx context.Context, userID string, friendID string)) *MockFriendshipRepository_IsFriend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_IsFriend_Call) Return(b bool, err error) *MockFriendshipRepository_IsFriend_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFriendshipRepository_IsFriend_Call) RunAndReturn(run func(ctx context.Context, userID string, friendID string) (bool, error)) *MockFriendshipRepository_IsFriend_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFriend provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) RemoveFriend(ctx context.Context, userID string, friendID string) (bool, error) {
	ret := _mock.Called(ctx, userID, friendID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFriend")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, userID, friendID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, userID, friendID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, friendID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_RemoveFriend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFriend'
type MockFriendshipRepository_RemoveFriend_Call struct {
	*mock.Call
}

// RemoveFriend is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - friendID string
func (_e *MockFriendshipRepository_Expecter) RemoveFriend(ctx interface{}, userID interface{}, friendID interface{}) *MockFriendshipRepository_RemoveFriend_Call {
	return &MockFriendshipRepository_RemoveFriend_Call{Call: _e.mock.On("RemoveFriend", ctx, userID, friendID)}
}

func (_c *MockFriendshipRepository_RemoveFriend_Call) Run(run func(ctx context.Context, userID string, friendID string)) *MockFriendshipRepository_RemoveFriend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_RemoveFriend_Call) Return(b bool, err error) *MockFriendshipRepository_RemoveFriend_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFriendshipRepository_RemoveFriend_Call) RunAndReturn(run func(ctx context.Context, userID string, friendID string) (bool, error)) *MockFriendshipRepository_RemoveFriend_Call {
	_c.Call.Return(run)
	return _c
}
