// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"friends_service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// GetUsersByUsername provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUsersByUsername(ctx context.Context, name string, cursor string) ([]*domain.User, error) {
	ret := _mock.Called(ctx, name, cursor)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByUsername")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*domain.User, error)); ok {
		return returnFunc(ctx, name, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*domain.User); ok {
		r0 = returnFunc(ctx, name, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, cursor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUsersByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersByUsername'
type MockUserRepository_GetUsersByUsername_Call struct {
	*mock.Call
}

// GetUsersByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - cursor string
func (_e *MockUserRepository_Expecter) GetUsersByUsername(ctx interface{}, name interface{}, cursor interface{}) *MockUserRepository_GetUsersByUsername_Call {
	return &MockUserRepository_GetUsersByUsername_Call{Call: _e.mock.On("GetUsersByUsername", ctx, name, cursor)}
}

func (_c *MockUserRepository_GetUsersByUsername_Call) Run(run func(ctx context.Context, name string, cursor string)) *MockUserRepository_GetUsersByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUsersByUsername_Call) Return(users []*domain.User, err error) *MockUserRepository_GetUsersByUsername_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepository_GetUsersByUsername_Call) RunAndReturn(run func(ctx context.Context, name string, cursor string) ([]*domain.User, error)) *MockUserRepository_GetUsersByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// UserExists provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) UserExists(ctx context.Context, userID string) (bool, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UserExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_UserExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserExists'
type MockUserRepository_UserExists_Call struct {
	*mock.Call
}

// UserExists is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) UserExists(ctx interface{}, userID interface{}) *MockUserRepository_UserExists_Call {
	return &MockUserRepository_UserExists_Call{Call: _e.mock.On("UserExists", ctx, userID)}
}

func (_c *MockUserRepository_UserExists_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepository_UserExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_UserExists_Call) Return(b bool, err error) *MockUserRepository_UserExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepository_UserExists_Call) RunAndReturn(run func(ctx context.Context, userID string) (bool, error)) *MockUserRepository_UserExists_Call {
	_c.Call.Return(run)
	return _c
}
