// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"friends_service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFriendship creates a new instance of MockFriendship. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFriendship(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFriendship {
	mock := &MockFriendship{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFriendship is an autogenerated mock type for the Friendship type
type MockFriendship struct {
	mock.Mock
}

type MockFriendship_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFriendship) EXPECT() *MockFriendship_Expecter {
	return &MockFriendship_Expecter{mock: &_m.Mock}
}

// AcceptFriendRequest provides a mock function for the type MockFriendship
func (_mock *MockFriendship) AcceptFriendRequest(ctx context.Context, userID string, inviterID string) error {
	ret := _mock.Called(ctx, userID, inviterID)

	if len(ret) == 0 {
		panic("no return value specified for AcceptFriendRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, inviterID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFriendship_AcceptFriendRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptFriendRequest'
type MockFriendship_AcceptFriendRequest_Call struct {
	*mock.Call
}

// AcceptFriendRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - inviterID string
func (_e *MockFriendship_Expecter) AcceptFriendRequest(ctx interface{}, userID interface{}, inviterID interface{}) *MockFriendship_AcceptFriendRequest_Call {
	return &MockFriendship_AcceptFriendRequest_Call{Call: _e.mock.On("AcceptFriendRequest", ctx, userID, inviterID)}
}

func (_c *MockFriendship_AcceptFriendRequest_Call) Run(run func(ctx context.Context, userID string, inviterID string)) *MockFriendship_AcceptFriendRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendship_AcceptFriendRequest_Call) Return(err error) *MockFriendship_AcceptFriendRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFriendship_AcceptFriendRequest_Call) RunAndReturn(run func(ctx context.Context, userID string, inviterID string) error) *MockFriendship_AcceptFriendRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CancelFriendRequest provides a mock function for the type MockFriendship
func (_mock *MockFriendship) CancelFriendRequest(ctx context.Context, userID string, inviteeID string) error {
	ret := _mock.Called(ctx, userID, inviteeID)

	if len(ret) == 0 {
		panic("no return value specified for CancelFriendRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, inviteeID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFriendship_CancelFriendRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelFriendRequest'
type MockFriendship_CancelFriendRequest_Call struct {
	*mock.Call
}

// CancelFriendRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - inviteeID string
func (_e *MockFriendship_Expecter) CancelFriendRequest(ctx interface{}, userID interface{}, inviteeID interface{}) *MockFriendship_CancelFriendRequest_Call {
	return &MockFriendship_CancelFriendRequest_Call{Call: _e.mock.On("CancelFriendRequest", ctx, userID, inviteeID)}
}

func (_c *MockFriendship_CancelFriendRequest_Call) Run(run func(ctx context.Context, userID string, inviteeID string)) *MockFriendship_CancelFriendRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendship_CancelFriendRequest_Call) Return(err error) *MockFriendship_CancelFriendRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFriendship_CancelFriendRequest_Call) RunAndReturn(run func(ctx context.Context, userID string, inviteeID string) error) *MockFriendship_CancelFriendRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DeclineFriendRequest provides a mock function for the type MockFriendship
func (_mock *MockFriendship) DeclineFriendRequest(ctx context.Context, userID string, inviterID string) error {
	ret := _mock.Called(ctx, userID, inviterID)

	if len(ret) == 0 {
		panic("no return value specified for DeclineFriendRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, inviterID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFriendship_DeclineFriendRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeclineFriendRequest'
type MockFriendship_DeclineFriendRequest_Call struct {
	*mock.Call
}

// DeclineFriendRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - inviterID string
func (_e *MockFriendship_Expecter) DeclineFriendRequest(ctx interface{}, userID interface{}, inviterID interface{}) *MockFriendship_DeclineFriendRequest_Call {
	return &MockFriendship_DeclineFriendRequest_Call{Call: _e.mock.On("DeclineFriendRequest", ctx, userID, inviterID)}
}

func (_c *MockFriendship_DeclineFriendRequest_Call) Run(run func(ctx context.Context, userID string, inviterID string)) *MockFriendship_DeclineFriendRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendship_DeclineFriendRequest_Call) Return(err error) *MockFriendship_DeclineFriendRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFriendship_DeclineFriendRequest_Call) RunAndReturn(run func(ctx context.Context, userID string, inviterID string) error) *MockFriendship_DeclineFriendRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetFriendsList provides a mock function for the type MockFriendship
func (_mock *MockFriendship) GetFriendsList(ctx context.Context, userID string) ([]*domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFriendsList")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendship_GetFriendsList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFriendsList'
type MockFriendship_GetFriendsList_Call struct {
	*mock.Call
}

// GetFriendsList is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockFriendship_Expecter) GetFriendsList(ctx interface{}, userID interface{}) *MockFriendship_GetFriendsList_Call {
	return &MockFriendship_GetFriendsList_Call{Call: _e.mock.On("GetFriendsList", ctx, userID)}
}

func (_c *MockFriendship_GetFriendsList_Call) Run(run func(ctx context.Context, userID string)) *MockFriendship_GetFriendsList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFriendship_GetFriendsList_Call) Return(users []*domain.User, err error) *MockFriendship_GetFriendsList_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockFriendship_GetFriendsList_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*domain.User, error)) *MockFriendship_GetFriendsList_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvites provides a mock function for the type MockFriendship
func (_mock *MockFriendship) GetInvites(ctx context.Context, userID string) ([]*domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetInvites")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendship_GetInvites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvites'
type MockFriendship_GetInvites_Call struct {
	*mock.Call
}

// GetInvites is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockFriendship_Expecter) GetInvites(ctx interface{}, userID interface{}) *MockFriendship_GetInvites_Call {
	return &MockFriendship_GetInvites_Call{Call: _e.mock.On("GetInvites", ctx, userID)}
}

func (_c *MockFriendship_GetInvites_Call) Run(run func(ctx context.Context, userID string)) *MockFriendship_GetInvites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFriendship_GetInvites_Call) Return(users []*domain.User, err error) *MockFriendship_GetInvites_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockFriendship_GetInvites_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*domain.User, error)) *MockFriendship_GetInvites_Call {
	_c.Call.Return(run)
	return _c
}

// IsFriend provides a mock function for the type MockFriendship
func (_mock *MockFriendship) IsFriend(ctx context.Context, userID string, friendID string) (bool, error) {
	ret := _mock.Called(ctx, userID, friendID)

	if len(ret) == 0 {
		panic("no return value specified for IsFriend")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, userID, friendID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, userID, friendID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, friendID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendship_IsFriend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFriend'
type MockFriendship_IsFriend_Call struct {
	*mock.Call
}

// IsFriend is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - friendID string
func (_e *MockFriendship_Expecter) IsFriend(ctx interface{}, userID interface{}, friendID interface{}) *MockFriendship_IsFriend_Call {
	return &MockFriendship_IsFriend_Call{Call: _e.mock.On("IsFriend", ctx, userID, friendID)}
}

func (_c *MockFriendship_IsFriend_Call) Run(run func(ctx context.Context, userID string, friendID string)) *MockFriendship_IsFriend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendship_IsFriend_Call) Return(b bool, err error) *MockFriendship_IsFriend_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFriendship_IsFriend_Call) RunAndReturn(run func(ctx context.Context, userID string, friendID string) (bool, error)) *MockFriendship_IsFriend_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFriend provides a mock function for the type MockFriendship
func (_mock *MockFriendship) RemoveFriend(ctx context.Context, userID string, friendID string) error {
	ret := _mock.Called(ctx, userID, friendID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFriend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, friendID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFriendship_RemoveFriend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFriend'
type MockFriendship_RemoveFriend_Call struct {
	*mock.Call
}

// RemoveFriend is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - friendID string
func (_e *MockFriendship_Expecter) RemoveFriend(ctx interface{}, userID interface{}, friendID interface{}) *MockFriendship_RemoveFriend_Call {
	return &MockFriendship_RemoveFriend_Call{Call: _e.mock.On("RemoveFriend", ctx, userID, friendID)}
}

func (_c *MockFriendship_RemoveFriend_Call) Run(run func(ctx context.Context, userID string, friendID string)) *MockFriendship_RemoveFriend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendship_RemoveFriend_Call) Return(err error) *MockFriendship_RemoveFriend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFriendship_RemoveFriend_Call) RunAndReturn(run func(ctx context.Context, userID string, friendID string) error) *MockFriendship_RemoveFriend_Call {
	_c.Call.Return(run)
	return _c
}

// SearchFriend provides a mock function for the type MockFriendship
func (_mock *MockFriendship) SearchFriend(ctx context.Context, userID string, searchUsername string, cursor string) ([]*domain.User, error) {
	ret := _mock.Called(ctx, userID, searchUsername, cursor)

	if len(ret) == 0 {
		panic("no return value specified for SearchFriend")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]*domain.User, error)); ok {
		return returnFunc(ctx, userID, searchUsername, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []*domain.User); ok {
		r0 = returnFunc(ctx, userID, searchUsername, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, searchUsername, cursor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendship_SearchFriend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchFriend'
type MockFriendship_SearchFriend_Call struct {
	*mock.Call
}

// SearchFriend is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - searchUsername string
//   - cursor string
func (_e *MockFriendship_Expecter) SearchFriend(ctx interface{}, userID interface{}, searchUsername interface{}, cursor interface{}) *MockFriendship_SearchFriend_Call {
	return &MockFriendship_SearchFriend_Call{Call: _e.mock.On("SearchFriend", ctx, userID, searchUsername, cursor)}
}

func (_c *MockFriendship_SearchFriend_Call) Run(run func(ctx context.Context, userID string, searchUsername string, cursor string)) *MockFriendship_SearchFriend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFriendship_SearchFriend_Call) Return(users []*domain.User, err error) *MockFriendship_SearchFriend_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockFriendship_SearchFriend_Call) RunAndReturn(run func(ctx context.Context, userID string, searchUsername string, cursor string) ([]*domain.User, error)) *MockFriendship_SearchFriend_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUser provides a mock function for the type MockFriendship
func (_mock *MockFriendship) SearchUser(ctx context.Context, username string, cursor string) ([]*domain.User, error) {
	ret := _mock.Called(ctx, username, cursor)

	if len(ret) == 0 {
		panic("no return value specified for SearchUser")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*domain.User, error)); ok {
		return returnFunc(ctx, username, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*domain.User); ok {
		r0 = returnFunc(ctx, username, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, cursor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendship_SearchUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUser'
type MockFriendship_SearchUser_Call struct {
	*mock.Call
}

// SearchUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - cursor string
func (_e *MockFriendship_Expecter) SearchUser(ctx interface{}, username interface{}, cursor interface{}) *MockFriendship_SearchUser_Call {
	return &MockFriendship_SearchUser_Call{Call: _e.mock.On("SearchUser", ctx, username, cursor)}
}

func (_c *MockFriendship_SearchUser_Call) Run(run func(ctx context.Context, username string, cursor string)) *MockFriendship_SearchUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendship_SearchUser_Call) Return(users []*domain.User, err error) *MockFriendship_SearchUser_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockFriendship_SearchUser_Call) RunAndReturn(run func(ctx context.Context, username string, cursor string) ([]*domain.User, error)) *MockFriendship_SearchUser_Call {
	_c.Call.Return(run)
	return _c
}

// SendFriendRequest provides a mock function for the type MockFriendship
func (_mock *MockFriendship) SendFriendRequest(ctx context.Context, inviterID string, inviteeID string) error {
	ret := _mock.Called(ctx, inviterID, inviteeID)

	if len(ret) == 0 {
		panic("no return value specified for SendFriendRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, inviterID, inviteeID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFriendship_SendFriendRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendFriendRequest'
type MockFriendship_SendFriendRequest_Call struct {
	*mock.Call
}

// SendFriendRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - inviterID string
//   - inviteeID string
func (_e *MockFriendship_Expecter) SendFriendRequest(ctx interface{}, inviterID interface{}, inviteeID interface{}) *MockFriendship_SendFriendRequest_Call {
	return &MockFriendship_SendFriendRequest_Call{Call: _e.mock.On("SendFriendRequest", ctx, inviterID, inviteeID)}
}

func (_c *MockFriendship_SendFriendRequest_Call) Run(run func(ctx context.Context, inviterID string, inviteeID string)) *MockFriendship_SendFriendRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendship_SendFriendRequest_Call) Return(err error) *MockFriendship_SendFriendRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFriendship_SendFriendRequest_Call) RunAndReturn(run func(ctx context.Context, inviterID string, inviteeID string) error) *MockFriendship_SendFriendRequest_Call {
	_c.Call.Return(run)
	return _c
}
