// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"auth_service/internal/domain"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) CreateSession(ctx context.Context, userID string, name string, refreshToken string, expiresAt time.Time) error {
	ret := _mock.Called(ctx, userID, name, refreshToken, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, name, refreshToken, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - name string
//   - refreshToken string
//   - expiresAt time.Time
func (_e *MockSessionRepository_Expecter) CreateSession(ctx interface{}, userID interface{}, name interface{}, refreshToken interface{}, expiresAt interface{}) *MockSessionRepository_CreateSession_Call {
	return &MockSessionRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID, name, refreshToken, expiresAt)}
}

func (_c *MockSessionRepository_CreateSession_Call) Run(run func(ctx context.Context, userID string, name string, refreshToken string, expiresAt time.Time)) *MockSessionRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockSessionRepository_CreateSession_Call) Return(err error) *MockSessionRepository_CreateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_CreateSession_Call) RunAndReturn(run func(ctx context.Context, userID string, name string, refreshToken string, expiresAt time.Time) error) *MockSessionRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) DeleteSession(ctx context.Context, refreshToken string) (*domain.Session, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Session, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Session); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockSessionRepository_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockSessionRepository_Expecter) DeleteSession(ctx interface{}, refreshToken interface{}) *MockSessionRepository_DeleteSession_Call {
	return &MockSessionRepository_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, refreshToken)}
}

func (_c *MockSessionRepository_DeleteSession_Call) Run(run func(ctx context.Context, refreshToken string)) *MockSessionRepository_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_DeleteSession_Call) Return(session *domain.Session, err error) *MockSessionRepository_DeleteSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*domain.Session, error)) *MockSessionRepository_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSessionsByUserID provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) DeleteSessionsByUserID(ctx context.Context, userID string) ([]*domain.Session, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSessionsByUserID")
	}

	var r0 []*domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Session, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Session); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_DeleteSessionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSessionsByUserID'
type MockSessionRepository_DeleteSessionsByUserID_Call struct {
	*mock.Call
}

// DeleteSessionsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockSessionRepository_Expecter) DeleteSessionsByUserID(ctx interface{}, userID interface{}) *MockSessionRepository_DeleteSessionsByUserID_Call {
	return &MockSessionRepository_DeleteSessionsByUserID_Call{Call: _e.mock.On("DeleteSessionsByUserID", ctx, userID)}
}

func (_c *MockSessionRepository_DeleteSessionsByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockSessionRepository_DeleteSessionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_DeleteSessionsByUserID_Call) Return(sessions []*domain.Session, err error) *MockSessionRepository_DeleteSessionsByUserID_Call {
	_c.Call.Return(sessions, err)
	return _c
}

func (_c *MockSessionRepository_DeleteSessionsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*domain.Session, error)) *MockSessionRepository_DeleteSessionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByToken provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) GetSessionByToken(ctx context.Context, refreshToken string) (*domain.Session, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByToken")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Session, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Session); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_GetSessionByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByToken'
type MockSessionRepository_GetSessionByToken_Call struct {
	*mock.Call
}

// GetSessionByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockSessionRepository_Expecter) GetSessionByToken(ctx interface{}, refreshToken interface{}) *MockSessionRepository_GetSessionByToken_Call {
	return &MockSessionRepository_GetSessionByToken_Call{Call: _e.mock.On("GetSessionByToken", ctx, refreshToken)}
}

func (_c *MockSessionRepository_GetSessionByToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockSessionRepository_GetSessionByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_GetSessionByToken_Call) Return(session *domain.Session, err error) *MockSessionRepository_GetSessionByToken_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_GetSessionByToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*domain.Session, error)) *MockSessionRepository_GetSessionByToken_Call {
	_c.Call.Return(run)
	return _c
}
