// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: get_status.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusReq) Reset() {
	*x = GetStatusReq{}
	mi := &file_get_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusReq) ProtoMessage() {}

func (x *GetStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_get_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusReq.ProtoReflect.Descriptor instead.
func (*GetStatusReq) Descriptor() ([]byte, []int) {
	return file_get_status_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatusReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetStatusRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      []*MapMetadata         `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRes) Reset() {
	*x = GetStatusRes{}
	mi := &file_get_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRes) ProtoMessage() {}

func (x *GetStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_get_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRes.ProtoReflect.Descriptor instead.
func (*GetStatusRes) Descriptor() ([]byte, []int) {
	return file_get_status_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusRes) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetStatusRes) GetMetadata() []*MapMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_get_status_proto protoreflect.FileDescriptor

const file_get_status_proto_rawDesc = "" +
	"\n" +
	"\x10get_status.proto\x1a\fcommon.proto\"'\n" +
	"\fGetStatusReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Y\n" +
	"\fGetStatusRes\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\v2\a.StatusR\x06status\x12(\n" +
	"\bmetadata\x18\x02 \x03(\v2\f.MapMetadataR\bmetadataB\x19Z\x17presence_service/pkg/pbb\x06proto3"

var (
	file_get_status_proto_rawDescOnce sync.Once
	file_get_status_proto_rawDescData []byte
)

func file_get_status_proto_rawDescGZIP() []byte {
	file_get_status_proto_rawDescOnce.Do(func() {
		file_get_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_get_status_proto_rawDesc), len(file_get_status_proto_rawDesc)))
	})
	return file_get_status_proto_rawDescData
}

var file_get_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_get_status_proto_goTypes = []any{
	(*GetStatusReq)(nil), // 0: GetStatusReq
	(*GetStatusRes)(nil), // 1: GetStatusRes
	(*Status)(nil),       // 2: Status
	(*MapMetadata)(nil),  // 3: MapMetadata
}
var file_get_status_proto_depIdxs = []int32{
	2, // 0: GetStatusRes.status:type_name -> Status
	3, // 1: GetStatusRes.metadata:type_name -> MapMetadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_get_status_proto_init() }
func file_get_status_proto_init() {
	if File_get_status_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_status_proto_rawDesc), len(file_get_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_status_proto_goTypes,
		DependencyIndexes: file_get_status_proto_depIdxs,
		MessageInfos:      file_get_status_proto_msgTypes,
	}.Build()
	File_get_status_proto = out.File
	file_get_status_proto_goTypes = nil
	file_get_status_proto_depIdxs = nil
}
