// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: mark_online.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarkOnlineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Metadata      []*MapMetadata         `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkOnlineReq) Reset() {
	*x = MarkOnlineReq{}
	mi := &file_mark_online_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkOnlineReq) ProtoMessage() {}

func (x *MarkOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_mark_online_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkOnlineReq.ProtoReflect.Descriptor instead.
func (*MarkOnlineReq) Descriptor() ([]byte, []int) {
	return file_mark_online_proto_rawDescGZIP(), []int{0}
}

func (x *MarkOnlineReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MarkOnlineReq) GetMetadata() []*MapMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_mark_online_proto protoreflect.FileDescriptor

const file_mark_online_proto_rawDesc = "" +
	"\n" +
	"\x11mark_online.proto\x1a\fcommon.proto\"R\n" +
	"\rMarkOnlineReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\bmetadata\x18\x02 \x03(\v2\f.MapMetadataR\bmetadataB\x19Z\x17presence_service/pkg/pbb\x06proto3"

var (
	file_mark_online_proto_rawDescOnce sync.Once
	file_mark_online_proto_rawDescData []byte
)

func file_mark_online_proto_rawDescGZIP() []byte {
	file_mark_online_proto_rawDescOnce.Do(func() {
		file_mark_online_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mark_online_proto_rawDesc), len(file_mark_online_proto_rawDesc)))
	})
	return file_mark_online_proto_rawDescData
}

var file_mark_online_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mark_online_proto_goTypes = []any{
	(*MarkOnlineReq)(nil), // 0: MarkOnlineReq
	(*MapMetadata)(nil),   // 1: MapMetadata
}
var file_mark_online_proto_depIdxs = []int32{
	1, // 0: MarkOnlineReq.metadata:type_name -> MapMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mark_online_proto_init() }
func file_mark_online_proto_init() {
	if File_mark_online_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mark_online_proto_rawDesc), len(file_mark_online_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mark_online_proto_goTypes,
		DependencyIndexes: file_mark_online_proto_depIdxs,
		MessageInfos:      file_mark_online_proto_msgTypes,
	}.Build()
	File_mark_online_proto = out.File
	file_mark_online_proto_goTypes = nil
	file_mark_online_proto_depIdxs = nil
}
