// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: presence.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_presence_proto protoreflect.FileDescriptor

const file_presence_proto_rawDesc = "" +
	"\n" +
	"\x0epresence.proto\x1a\fcommon.proto\x1a\x15get_bulk_status.proto\x1a\x10get_status.proto\x1a\x0fheartbeat.proto\x1a\x11mark_online.proto2\xc0\x01\n" +
	"\bPresence\x12'\n" +
	"\n" +
	"MarkOnline\x12\x0e.MarkOnlineReq\x1a\a.Status\"\x00\x12%\n" +
	"\tHeartbeat\x12\r.HeartbeatReq\x1a\a.Status\"\x00\x12+\n" +
	"\tGetStatus\x12\r.GetStatusReq\x1a\r.GetStatusRes\"\x00\x127\n" +
	"\rGetBulkStatus\x12\x11.GetBulkStatusReq\x1a\x11.GetBulkStatusRes\"\x00B\x19Z\x17presence_service/pkg/pbb\x06proto3"

var file_presence_proto_goTypes = []any{
	(*MarkOnlineReq)(nil),    // 0: MarkOnlineReq
	(*HeartbeatReq)(nil),     // 1: HeartbeatReq
	(*GetStatusReq)(nil),     // 2: GetStatusReq
	(*GetBulkStatusReq)(nil), // 3: GetBulkStatusReq
	(*Status)(nil),           // 4: Status
	(*GetStatusRes)(nil),     // 5: GetStatusRes
	(*GetBulkStatusRes)(nil), // 6: GetBulkStatusRes
}
var file_presence_proto_depIdxs = []int32{
	0, // 0: Presence.MarkOnline:input_type -> MarkOnlineReq
	1, // 1: Presence.Heartbeat:input_type -> HeartbeatReq
	2, // 2: Presence.GetStatus:input_type -> GetStatusReq
	3, // 3: Presence.GetBulkStatus:input_type -> GetBulkStatusReq
	4, // 4: Presence.MarkOnline:output_type -> Status
	4, // 5: Presence.Heartbeat:output_type -> Status
	5, // 6: Presence.GetStatus:output_type -> GetStatusRes
	6, // 7: Presence.GetBulkStatus:output_type -> GetBulkStatusRes
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_presence_proto_init() }
func file_presence_proto_init() {
	if File_presence_proto != nil {
		return
	}
	file_common_proto_init()
	file_get_bulk_status_proto_init()
	file_get_status_proto_init()
	file_heartbeat_proto_init()
	file_mark_online_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_presence_proto_rawDesc), len(file_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_presence_proto_goTypes,
		DependencyIndexes: file_presence_proto_depIdxs,
	}.Build()
	File_presence_proto = out.File
	file_presence_proto_goTypes = nil
	file_presence_proto_depIdxs = nil
}
