// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: get_bulk_status.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBulkStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBulkStatusReq) Reset() {
	*x = GetBulkStatusReq{}
	mi := &file_get_bulk_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBulkStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBulkStatusReq) ProtoMessage() {}

func (x *GetBulkStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_get_bulk_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBulkStatusReq.ProtoReflect.Descriptor instead.
func (*GetBulkStatusReq) Descriptor() ([]byte, []int) {
	return file_get_bulk_status_proto_rawDescGZIP(), []int{0}
}

func (x *GetBulkStatusReq) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetBulkStatusRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UserInfo      []*UserInfo            `protobuf:"bytes,2,rep,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBulkStatusRes) Reset() {
	*x = GetBulkStatusRes{}
	mi := &file_get_bulk_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBulkStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBulkStatusRes) ProtoMessage() {}

func (x *GetBulkStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_get_bulk_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBulkStatusRes.ProtoReflect.Descriptor instead.
func (*GetBulkStatusRes) Descriptor() ([]byte, []int) {
	return file_get_bulk_status_proto_rawDescGZIP(), []int{1}
}

func (x *GetBulkStatusRes) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetBulkStatusRes) GetUserInfo() []*UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

var File_get_bulk_status_proto protoreflect.FileDescriptor

const file_get_bulk_status_proto_rawDesc = "" +
	"\n" +
	"\x15get_bulk_status.proto\x1a\fcommon.proto\"-\n" +
	"\x10GetBulkStatusReq\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"[\n" +
	"\x10GetBulkStatusRes\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\v2\a.StatusR\x06status\x12&\n" +
	"\tuser_info\x18\x02 \x03(\v2\t.UserInfoR\buserInfoB\x19Z\x17presence_service/pkg/pbb\x06proto3"

var (
	file_get_bulk_status_proto_rawDescOnce sync.Once
	file_get_bulk_status_proto_rawDescData []byte
)

func file_get_bulk_status_proto_rawDescGZIP() []byte {
	file_get_bulk_status_proto_rawDescOnce.Do(func() {
		file_get_bulk_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_get_bulk_status_proto_rawDesc), len(file_get_bulk_status_proto_rawDesc)))
	})
	return file_get_bulk_status_proto_rawDescData
}

var file_get_bulk_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_get_bulk_status_proto_goTypes = []any{
	(*GetBulkStatusReq)(nil), // 0: GetBulkStatusReq
	(*GetBulkStatusRes)(nil), // 1: GetBulkStatusRes
	(*Status)(nil),           // 2: Status
	(*UserInfo)(nil),         // 3: UserInfo
}
var file_get_bulk_status_proto_depIdxs = []int32{
	2, // 0: GetBulkStatusRes.status:type_name -> Status
	3, // 1: GetBulkStatusRes.user_info:type_name -> UserInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_get_bulk_status_proto_init() }
func file_get_bulk_status_proto_init() {
	if File_get_bulk_status_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_bulk_status_proto_rawDesc), len(file_get_bulk_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_bulk_status_proto_goTypes,
		DependencyIndexes: file_get_bulk_status_proto_depIdxs,
		MessageInfos:      file_get_bulk_status_proto_msgTypes,
	}.Build()
	File_get_bulk_status_proto = out.File
	file_get_bulk_status_proto_goTypes = nil
	file_get_bulk_status_proto_depIdxs = nil
}
